/*
 Galleria v 1.2 2011-02-18
 http://galleria.aino.se

 Copyright (c) 2011, Aino
 Licensed under the MIT license.
*/
(function(e){var i=this,m=i.document,u=e(m),z=!1,p=navigator.userAgent.toLowerCase(),E=i.location.hash.replace(/#\//,""),q=function(){return g.TOUCH?"touchstart":"click"},n,A=3,F=m.createElement("div"),I=F.getElementsByTagName("i");do F.innerHTML="<\!--[if gt IE "+ ++A+"]><i></i><![endif]--\>";while(I[0]);n=4<A?A:void 0;var r=function(){return{html:m.documentElement,body:m.body,head:m.getElementsByTagName("head")[0],title:m.title}},x=[];e.each("data ready thumbnail loadstart loadfinish image themeload play pause progress fullscreen_enter fullscreen_exit idle_enter idle_exit rescale lightbox_open lightbox_close lightbox_image".split(" "),
function(a,b){x.push(b);/_/.test(b)&&x.push(b.replace(/_/g,""))});var G=function(a){var b;if("object"!==typeof a)return a;e.each(a,function(d,c){/^[a-z]+_/.test(d)&&(b="",e.each(d.split("_"),function(a,c){b+=0<a?c.substr(0,1).toUpperCase()+c.substr(1):c}),a[b]=c,delete a[d])});return a},B=function(a){return-1<e.inArray(a,x)?g[a.toUpperCase()]:a},s={trunk:{},add:function(a,b,d,c){c=c||!1;this.clear(a);if(c)var e=b,b=function(){e();s.add(a,b,d)};this.trunk[a]=i.setTimeout(b,d)},clear:function(a){var b=
function(a){i.clearTimeout(this.trunk[a]);delete this.trunk[a]},d;if(a&&a in this.trunk)b.call(s,a);else if("undefined"===typeof a)for(d in this.trunk)this.trunk.hasOwnProperty(d)&&b.call(s,d)}},v=[],f={array:function(a){return Array.prototype.slice.call(a)},create:function(a,b){var d=m.createElement(b||"div");d.className=a;return d},forceStyles:function(a,b){a=e(a);a.attr("style")&&a.data("styles",a.attr("style")).removeAttr("style");a.css(b)},revertStyles:function(){e.each(f.array(arguments),function(a,
b){b=e(b).removeAttr("style");b.data("styles")&&b.attr("style",b.data("styles")).data("styles",null)})},moveOut:function(a){f.forceStyles(a,{position:"absolute",left:-1E4})},moveIn:function(){f.revertStyles.apply(f,f.array(arguments))},hide:function(a,b,d){a=e(a);a.data("opacity")||a.data("opacity",a.css("opacity"));var c={opacity:0};b?a.stop().animate(c,b,d):a.css(c)},show:function(a,b,d){var a=e(a),c=parseFloat(a.data("opacity"))||1,f={opacity:c};1===c&&a.data("opacity",null);b?a.stop().animate(f,
b,d):a.css(f)},addTimer:function(){s.add.apply(s,f.array(arguments));return this},clearTimer:function(){s.clear.apply(s,f.array(arguments));return this},wait:function(a){var a=e.extend({until:function(){return!1},success:function(){},error:function(){g.raise("Could not complete wait function.")},timeout:3E3},a),b=f.timestamp(),d,c,j=function(){c=f.timestamp();d=c-b;if(a.until(d))return a.success(),!1;if(c>=b+a.timeout)return a.error(),!1;i.setTimeout(j,2)};i.setTimeout(j,2)},toggleQuality:function(a,
b){7!==n||(8!==n||!a)||("undefined"===typeof b&&(b="nearest-neighbor"===a.style.msInterpolationMode),a.style.msInterpolationMode=b?"bicubic":"nearest-neighbor")},insertStyleTag:function(a){var b=m.createElement("style");r().head.appendChild(b);b.styleSheet?b.styleSheet.cssText=a:(a=m.createTextNode(a),b.appendChild(a))},loadScript:function(a,b){var d=!1,c=e("<script>").attr({src:a,async:!0}).get(0);c.onload=c.onreadystatechange=function(){if(!d&&(!this.readyState||"loaded"===this.readyState||"complete"===
this.readyState))d=!0,"function"===typeof b&&b.call(this,this),c.onload=c.onreadystatechange=null};var f=m.getElementsByTagName("script")[0];f.parentNode.insertBefore(c,f)},parseValue:function(a){return"number"===typeof a?a:"string"===typeof a?(a=a.match(/\-?\d/g))&&a.constructor===Array?parseInt(a.join(""),10):0:0},timestamp:function(){return(new Date).getTime()},loadCSS:function(a,b,d){var c,j=!1,l;e("link[rel=stylesheet]").each(function(){if(RegExp(a).test(this.href))return c=this,!1});"function"===
typeof b&&(d=b,b=void 0);d=d||function(){};if(c)return d.call(c,c),c;l=m.styleSheets.length;z&&(a+="?"+f.timestamp());e("#"+b).length?(e("#"+b).attr("href",a),l--,j=!0):(c=e("<link>").attr({rel:"stylesheet",href:a,id:b}).get(0),i.setTimeout(function(){var a=e('link[rel="stylesheet"], style');a.length?a.get(0).parentNode.insertBefore(c,a[0]):r().head.appendChild(c);n?c.attachEvent("onreadystatechange",function(){"complete"===c.readyState&&(j=!0)}):j=!0},10));"function"===typeof d&&f.wait({until:function(){return j&&
m.styleSheets.length>l},success:function(){f.addTimer("css",function(){d.call(c,c)},100)},error:function(){g.raise("Theme CSS could not load")},timeout:1E3});return c}},C={fade:function(a,b){e(a.next).css("opacity",0).show().animate({opacity:1},a.speed,b);a.prev&&e(a.prev).css("opacity",1).show().animate({opacity:0},a.speed)},flash:function(a,b){e(a.next).css("opacity",0);a.prev?e(a.prev).animate({opacity:0},a.speed/2,function(){e(a.next).animate({opacity:1},a.speed,b)}):e(a.next).animate({opacity:1},
a.speed,b)},pulse:function(a,b){a.prev&&e(a.prev).hide();e(a.next).css("opacity",0).animate({opacity:1},a.speed,b)},slide:function(a,b){var d=e(a.next).parent(),c=this.$("images"),f=this._stageWidth,g=this.getOptions("easing");d.css({left:f*(a.rewind?-1:1)});c.animate({left:f*(a.rewind?1:-1)},{duration:a.speed,queue:!1,easing:g,complete:function(){c.css("left",0);d.css("left",0);b()}})},fadeslide:function(a,b){var d=0,c=this.getOptions("easing"),g=this.getStageWidth();a.prev&&(d=f.parseValue(e(a.prev).css("left")),
e(a.prev).css({opacity:1,left:d}).animate({opacity:0,left:d+g*(a.rewind?1:-1)},{duration:a.speed,queue:!1,easing:c}));d=f.parseValue(e(a.next).css("left"));e(a.next).css({left:d+g*(a.rewind?-1:1),opacity:0}).animate({opacity:1,left:d},{duration:a.speed,complete:b,queue:!1,easing:c})}},g=function(){var a=this;this._theme=void 0;this._options={};this._playing=!1;this._playtime=5E3;this._active=null;this._queue={length:0};this._data=[];this._dom={};this._thumbnails=[];this._initialized=!1;this._stageHeight=
this._stageWidth=0;this._target=void 0;this._id=Math.random();e.each("container stage images image-nav image-nav-left image-nav-right info info-text info-title info-description info-author thumbnails thumbnails-list thumbnails-container thumb-nav-left thumb-nav-right loader counter tooltip".split(" "),function(b,c){a._dom[c]=f.create("galleria-"+c)});e.each(["current","total"],function(b,c){a._dom[c]=f.create("galleria-"+c,"span")});var b=this._keyboard={keys:{UP:38,DOWN:40,LEFT:37,RIGHT:39,RETURN:13,
ESCAPE:27,BACKSPACE:8,SPACE:32},map:{},bound:!1,press:function(c){var d=c.keyCode||c.which;d in b.map&&"function"===typeof b.map[d]&&b.map[d].call(a,c)},attach:function(a){var c,d;for(c in a)a.hasOwnProperty(c)&&(d=c.toUpperCase(),d in b.keys&&(b.map[b.keys[d]]=a[c]));b.bound||(b.bound=!0,u.bind("keydown",b.press))},detach:function(){b.bound=!1;u.unbind("keydown",b.press)}},d=this._controls={"0":void 0,1:void 0,active:0,swap:function(){d.active=d.active?0:1},getActive:function(){return d[d.active]},
getNext:function(){return d[1-d.active]}},c=this._carousel={next:a.$("thumb-nav-right"),prev:a.$("thumb-nav-left"),width:0,current:0,max:0,hooks:[],update:function(){var b=0,d=0,f=[0];e.each(a._thumbnails,function(a,c){c.ready&&(b+=c.outerWidth||e(c.container).outerWidth(!0),f[a+1]=b,d=Math.max(d,c.outerHeight||e(c.container).outerHeight(!0)))});a.$("thumbnails").css({width:b,height:d});c.max=b;c.hooks=f;c.width=a.$("thumbnails-list").width();c.setClasses();a.$("thumbnails-container").toggleClass("galleria-carousel",
b>c.width)},bindControls:function(){var b;c.next.bind(q(),function(d){d.preventDefault();if("auto"===a._options.carouselSteps)for(b=c.current;b<c.hooks.length;b++){if(c.hooks[b]-c.hooks[c.current]>c.width){c.set(b-2);break}}else c.set(c.current+a._options.carouselSteps)});c.prev.bind(q(),function(d){d.preventDefault();if("auto"===a._options.carouselSteps)for(b=c.current;0<=b;b--)if(c.hooks[c.current]-c.hooks[b]>c.width){c.set(b+2);break}else{if(0===b){c.set(0);break}}else c.set(c.current-a._options.carouselSteps)})},
set:function(a){for(a=Math.max(a,0);c.hooks[a-1]+c.width>=c.max&&0<=a;)a--;c.current=a;c.animate()},getLast:function(a){return(a||c.current)-1},follow:function(a){if(0===a||a===c.hooks.length-2)c.set(a);else{for(var b=c.current;c.hooks[b]-c.hooks[c.current]<c.width&&b<=c.hooks.length;)b++;a-1<c.current?c.set(a-1):a+2>b&&c.set(a-b+c.current+2)}},setClasses:function(){c.prev.toggleClass("disabled",!c.current);c.next.toggleClass("disabled",c.hooks[c.current]+c.width>=c.max)},animate:function(){c.setClasses();
var b=-1*c.hooks[c.current];isNaN(b)||a.$("thumbnails").animate({left:b},{duration:a._options.carouselSpeed,easing:a._options.easing,queue:!1})}},j=this._tooltip={initialized:!1,open:!1,init:function(){j.initialized=!0;f.insertStyleTag(".galleria-tooltip{padding:3px 8px;max-width:50%;background:#ffe;color:#000;z-index:3;position:absolute;font-size:11px;line-height:1.3opacity:0;box-shadow:0 0 2px rgba(0,0,0,.4);-moz-box-shadow:0 0 2px rgba(0,0,0,.4);-webkit-box-shadow:0 0 2px rgba(0,0,0,.4);}");a.$("tooltip").css("opacity",
0.8);f.hide(a.get("tooltip"))},move:function(b){var c=a.getMousePosition(b).x,b=a.getMousePosition(b).y,d=a.$("tooltip"),e=b,f=d.outerHeight(!0)+1,g=d.outerWidth(!0),j=f+15,g=a.$("container").width()-g-2,f=a.$("container").height()-f-2;!isNaN(c)&&!isNaN(e)&&(e-=30,c=Math.max(0,Math.min(g,c+10)),e=Math.max(0,Math.min(f,e)),b<j&&(e=j),d.css({left:c,top:e}))},bind:function(b,c){j.initialized||j.init();var d=function(b,c){j.define(b,c);e(b).hover(function(){f.clearTimer("switch_tooltip");a.$("container").unbind("mousemove",
j.move).bind("mousemove",j.move).trigger("mousemove");j.show(b);g.utils.addTimer("tooltip",function(){a.$("tooltip").stop().show();f.show(a.get("tooltip"),400);j.open=!0},j.open?0:500)},function(){a.$("container").unbind("mousemove",j.move);f.clearTimer("tooltip");a.$("tooltip").stop();f.hide(a.get("tooltip"),200,function(){a.$("tooltip").hide();f.addTimer("switch_tooltip",function(){j.open=!1},1E3)})})};"string"===typeof c?d(b in a._dom?a.get(b):b,c):e.each(b,function(b,c){d(a.get(b),c)})},show:function(b){var b=
e(b in a._dom?a.get(b):b),c=b.data("tt"),d=function(a){i.setTimeout(function(a){return function(){j.move(a)}}(a),10);b.unbind("mouseup",d)};if(c="function"===typeof c?c():c)a.$("tooltip").html(c.replace(/\s/,"&nbsp;")),b.bind("mouseup",d)},define:function(b,c){if("function"!==typeof c)var d=c,c=function(){return d};b=e(b in a._dom?a.get(b):b).data("tt",c);j.show(b)}},l=this._fullscreen={scrolled:0,active:!1,enter:function(b){l.active=!0;f.hide(a.getActiveImage());a.$("container").addClass("fullscreen");
l.scrolled=e(i).scrollTop();f.forceStyles(a.get("container"),{position:"fixed",top:0,left:0,width:"100%",height:"100%",zIndex:1E4});var c={height:"100%",overflow:"hidden",margin:0,padding:0};f.forceStyles(r().html,c);f.forceStyles(r().body,c);a.attachKeyboard({escape:a.exitFullscreen,right:a.next,left:a.prev});a.rescale(function(){f.addTimer("fullscreen_enter",function(){f.show(a.getActiveImage());"function"===typeof b&&b.call(a)},100);a.trigger(g.FULLSCREEN_ENTER)});e(i).resize(function(){l.scale()})},
scale:function(){a.rescale()},exit:function(b){l.active=!1;f.hide(a.getActiveImage());a.$("container").removeClass("fullscreen");f.revertStyles(a.get("container"),r().html,r().body);i.scrollTo(0,l.scrolled);a.detachKeyboard();a.rescale(function(){f.addTimer("fullscreen_exit",function(){f.show(a.getActiveImage());"function"===typeof b&&b.call(a)},50);a.trigger(g.FULLSCREEN_EXIT)});e(i).unbind("resize",l.scale)}},k=this._idle={trunk:[],bound:!1,add:function(a,b){if(a){k.bound||k.addEvent();var a=e(a),
c={},d;for(d in b)b.hasOwnProperty(d)&&(c[d]=a.css(d));a.data("idle",{from:c,to:b,complete:!0,busy:!1});k.addTimer();k.trunk.push(a)}},remove:function(b){b=jQuery(b);e.each(k.trunk,function(c,d){d.length&&!d.not(b).length&&(a._idle.show(b),a._idle.trunk.splice(c,1))});k.trunk.length||(k.removeEvent(),f.clearTimer("idle"))},addEvent:function(){k.bound=!0;a.$("container").bind("mousemove click",k.showAll)},removeEvent:function(){k.bound=!1;a.$("container").unbind("mousemove click",k.showAll)},addTimer:function(){f.addTimer("idle",
function(){a._idle.hide()},a._options.idleTime)},hide:function(){a.trigger(g.IDLE_ENTER);e.each(k.trunk,function(b,c){var d=c.data("idle");d&&(c.data("idle").complete=!1,c.stop().animate(d.to,{duration:a._options.idleSpeed,queue:!1,easing:"swing"}))})},showAll:function(){f.clearTimer("idle");e.each(a._idle.trunk,function(b,c){a._idle.show(c)})},show:function(b){var c=b.data("idle");!c.busy&&!c.complete&&(c.busy=!0,a.trigger(g.IDLE_EXIT),f.clearTimer("idle"),b.stop().animate(c.from,{duration:a._options.idleSpeed/
2,queue:!1,easing:"swing",complete:function(){e(this).data("idle").busy=!1;e(this).data("idle").complete=!0}}));k.addTimer()}},h=this._lightbox={width:0,height:0,initialized:!1,active:null,image:null,elems:{},init:function(){a.trigger(g.LIGHTBOX_OPEN);if(!h.initialized){h.initialized=!0;var b={},c=a._options,d="",c={overlay:"position:fixed;display:none;opacity:"+c.overlayOpacity+";filter:alpha(opacity="+100*c.overlayOpacity+");top:0;left:0;width:100%;height:100%;background:"+c.overlayBackground+";z-index:99990",
box:"position:fixed;display:none;width:400px;height:400px;top:50%;left:50%;margin-top:-200px;margin-left:-200px;z-index:99991",shadow:"position:absolute;background:#000;width:100%;height:100%;",content:"position:absolute;background-color:#fff;top:10px;left:10px;right:10px;bottom:10px;overflow:hidden",info:"position:absolute;bottom:10px;left:10px;right:10px;color:#444;font:11px/13px arial,sans-serif;height:13px",close:"position:absolute;top:10px;right:10px;height:20px;width:20px;background:#fff;text-align:center;cursor:pointer;color:#444;font:16px/22px arial,sans-serif;z-index:99999",
image:"position:absolute;top:10px;left:10px;right:10px;bottom:30px;overflow:hidden;display:block;",prevholder:"position:absolute;width:50%;top:0;bottom:40px;cursor:pointer;",nextholder:"position:absolute;width:50%;top:0;bottom:40px;right:-1px;cursor:pointer;",prev:"position:absolute;top:50%;margin-top:-20px;height:40px;width:30px;background:#fff;left:20px;display:none;line-height:40px;text-align:center;color:#000",next:"position:absolute;top:50%;margin-top:-20px;height:40px;width:30px;background:#fff;right:20px;left:auto;display:none;line-height:40px;text-align:center;color:#000",
title:"float:left",counter:"float:right;margin-left:8px;"},j={};8===n&&(c.nextholder+="background:#000;filter:alpha(opacity=0);",c.prevholder+="background:#000;filter:alpha(opacity=0);");e.each(c,function(a,b){d+=".galleria-lightbox-"+a+"{"+b+"}"});f.insertStyleTag(d);e.each("overlay box content shadow title info close prevholder prev nextholder next counter image".split(" "),function(c,d){a.addElement("lightbox-"+d);b[d]=h.elems[d]=a.get("lightbox-"+d)});h.image=new g.Picture;e.each({box:"shadow content close prevholder nextholder",
info:"title counter",content:"info image",prevholder:"prev",nextholder:"next"},function(a,b){var c=[];e.each(b.split(" "),function(a,b){c.push("lightbox-"+b)});j["lightbox-"+a]=c});a.append(j);e(b.image).append(h.image.container);e(r().body).append(b.overlay,b.box);e(b.close).bind(q(),h.hide).html("&#215;").hover(function(){e(this).css("color","#bbb")},function(){e(this).css("color","#444")});e.each(["Prev","Next"],function(a,c){var d=e(b[c.toLowerCase()]).html(/v/.test(c)?"&#8249;&nbsp;":"&nbsp;&#8250;"),
f=e(b[c.toLowerCase()+"holder"]);f.bind(q(),function(){h["show"+c]()});8>n?d.show():f.hover(function(){d.show()},function(){d.stop().fadeOut(200)})});e(b.overlay).bind(q(),h.hide)}},rescale:function(b){var c=Math.min(e(i).width()-40,h.width),d=Math.min(e(i).height()-60,h.height),d=Math.min(c/h.width,d/h.height),c=h.width*d+40,d=h.height*d+60,c={width:c,height:d,marginTop:-1*Math.ceil(d/2),marginLeft:-1*Math.ceil(c/2)};b?e(h.elems.box).css(c):e(h.elems.box).animate(c,a._options.lightboxTransitionSpeed,
a._options.easing,function(){var b=h.image,c=a._options.lightboxFadeSpeed;a.trigger({type:g.LIGHTBOX_IMAGE,imageTarget:b.image});b.show();f.show(b.image,c);f.show(h.elems.info,c)})},hide:function(){h.image.image=null;e(i).unbind("resize",h.rescale);e(h.elems.box).hide();f.hide(h.elems.info);f.hide(h.elems.overlay,200,function(){e(this).hide().css("opacity",a._options.overlayOpacity);a.trigger(g.LIGHTBOX_CLOSE)})},showNext:function(){h.show(a.getNext(h.active))},showPrev:function(){h.show(a.getPrev(h.active))},
show:function(b){h.active=b="number"===typeof b?b:a.getIndex();h.initialized||h.init();e(i).unbind("resize",h.rescale);var c=a.getData(b),d=a.getDataLength();f.hide(h.elems.info);h.image.load(c.image,function(a){h.width=a.original.width;h.height=a.original.height;e(a.image).css({width:"100.5%",height:"100.5%",top:0,zIndex:99998,opacity:0});h.elems.title.innerHTML=c.title;h.elems.counter.innerHTML=b+1+" / "+d;e(i).resize(h.rescale);h.rescale()});e(h.elems.overlay).show();e(h.elems.box).show()}};return this};
g.prototype={constructor:g,init:function(a,b){var d=this,b=G(b);v.push(this);this._original={target:a,options:b,data:null};(this._target=this._dom.target=a.nodeName?a:e(a).get(0))?(this._options={autoplay:!1,carousel:!0,carouselFollow:!0,carouselSpeed:400,carouselSteps:"auto",clicknext:!1,dataConfig:function(){return{}},dataSelector:"img",dataSource:this._target,debug:void 0,easing:"galleria",extend:function(){},height:"auto",idleTime:3E3,idleSpeed:200,imageCrop:!1,imageMargin:0,imagePan:!1,imagePanSmoothness:12,
imagePosition:"50%",keepSource:!1,lightboxFadeSpeed:200,lightboxTransition_speed:500,linkSourceTmages:!0,maxScaleRatio:void 0,minScaleRatio:void 0,overlayOpacity:0.85,overlayBackground:"#0b0b0b",pauseOnInteraction:!0,popupLinks:!1,preload:2,queue:!0,show:0,showInfo:!0,showCounter:!0,showImagenav:!0,thumbCrop:!0,thumbEventType:q(),thumbFit:!0,thumbMargin:0,thumbQuality:"auto",thumbnails:!0,transition:"fade",transitionInitial:void 0,transitionSpeed:400,width:"auto"},b&&!0===b.debug&&(z=!0),e(this._target).children().hide(),
g.theme?this._init():(f.addTimer("themeload",function(){g.raise("No theme found.",!0)},5E3),u.one(g.THEMELOAD,function(){f.clearTimer("themeload");d._init.call(d)}))):g.raise("Target not found.")},_init:function(){var a=this;if(this._initialized)return g.raise("Init failed: Gallery instance already initialized."),this;this._initialized=!0;if(!g.theme)return g.raise("Init failed: No theme found."),this;e.extend(!0,this._options,g.theme.defaults,this._original.options);this.bind(g.DATA,function(){this._original.data=
this._data;this.get("total").innerHTML=this.getDataLength();var b=this.$("container"),d={width:0,height:0},c=f.create("galleria-image");f.wait({until:function(){e.each(["width","height"],function(c,e){d[e]=a._options[e]&&"number"===typeof a._options[e]?a._options[e]:f.parseValue(b.css(e))||f.parseValue(a.$("target").css(e))||b[e]()||a.$("target")[e]()});var g=function(){return!0};a._options.thumbnails&&(a.$("thumbnails").append(c),g=function(){return!!e(c).height()});return g()&&d.width&&50<d.height},
success:function(){e(c).remove();b.width(d.width);b.height(d.height);g.WEBKIT?i.setTimeout(function(){a._run()},1):a._run()},error:function(){g.raise("Width & Height not found.",!0)},timeout:2E3})});this.bind(g.READY,function(b){return function(){f.show(this.$("counter"));this._options.carousel&&this._carousel.bindControls();this._options.autoplay&&(this.pause(),"number"===typeof this._options.autoplay&&(this._playtime=this._options.autoplay),this.trigger(g.PLAY),this._playing=!0);b?"number"===typeof this._options.show&&
this.show(this._options.show):(b=!0,this._options.clicknext&&(e.each(this._data,function(a,b){delete b.link}),this.$("stage").css({cursor:"pointer"}).bind(q(),function(){a.next()})),g.History&&g.History.change(function(b){b=parseInt(b.value.replace(/\//,""),10);isNaN(b)?i.history.go(-1):a.show(b,void 0,!0)}),g.theme.init.call(this,this._options),this._options.extend.call(this,this._options),/^[0-9]{1,4}$/.test(E)&&g.History?this.show(E,void 0,!0):this.show(this._options.show))}}(!1));this.append({"info-text":["info-title",
"info-description","info-author"],info:["info-text"],"image-nav":["image-nav-right","image-nav-left"],stage:["images","loader","counter","image-nav"],"thumbnails-list":["thumbnails"],"thumbnails-container":["thumb-nav-left","thumbnails-list","thumb-nav-right"],container:["stage","thumbnails-container","info","tooltip"]});f.hide(this.$("counter").append(this.get("current")," / ",this.get("total")));this.setCounter("&#8211;");f.hide(a.get("tooltip"));e.each(Array(2),function(b){var d=new g.Picture;
e(d.container).css({position:"absolute",top:0,left:0});a.$("images").append(d.container);a._controls[b]=d});this.$("images").css({position:"relative",top:0,left:0,width:"100%",height:"100%"});this.$("thumbnails, thumbnails-list").css({overflow:"hidden",position:"relative"});this.$("image-nav-right, image-nav-left").bind(q(),function(b){a._options.clicknext&&b.stopPropagation();a._options.pause_on_interaction&&a.pause();b=/right/.test(this.className)?"next":"prev";a[b]()});e.each(["info","counter",
"image-nav"],function(b,d){!1===a._options["show_"+d.replace(/-/,"")]&&f.moveOut(a.get(d))});this.load();!this._options.keep_source&&!n&&(this._target.innerHTML="");this.$("target").append(this.get("container"));this._options.carousel&&this.bind(g.THUMBNAIL,function(){this.updateCarousel()});return this},_createThumbnails:function(){var a,b,d,c,j,l=this,k=this._options,h;a=l.$("thumbnails").find(".active");h=a.length?a.find("img").attr("src"):!1;var D="string"===typeof k.thumbnails?k.thumbnails.toLowerCase():
null,n=function(a){return m.defaultView&&m.defaultView.getComputedStyle?m.defaultView.getComputedStyle(d.container,null)[a]:j.css(a)},y=function(a,b,c){return function(){e(c).append(a);l.trigger({type:g.THUMBNAIL,thumbTarget:a,index:b})}},t=function(a){k.pauseOnInteraction&&l.pause();var b=e(a.currentTarget).data("index");l.getIndex()!==b&&l.show(b);a.preventDefault()},w=function(a){a.scale({width:a.data.width,height:a.data.height,crop:k.thumbCrop,margin:k.thumbMargin,complete:function(a){var b=["left",
"top"],c,d;e.each(["Width","Height"],function(f,g){c=g.toLowerCase();if((!0!==k.thumbCrop||k.thumbCrop===c)&&k.thumbFit)d={},d[c]=a[c],e(a.container).css(d),d={},d[b[f]]=0,e(a.image).css(d).attr("alt",e(a.container).data("alt"));a["outer"+g]=e(a.container)["outer"+g](!0)});f.toggleQuality(a.image,!0===k.thumbQuality||"auto"===k.thumbQuality&&a.original.width<3*a.width);l.trigger({type:g.THUMBNAIL,thumbTarget:a.image,index:a.data.order})}})};this._thumbnails=[];this.$("thumbnails").empty();for(a=0;this._data[a];a++)c=
this._data[a],!0===k.thumbnails?(d=new g.Picture(a),b=c.thumb||c.image,this.$("thumbnails").append(d.container),j=e(d.container),d.data={width:f.parseValue(n("width")),height:f.parseValue(n("height")),order:a},k.thumbFit&&!0!==k.thumbCrop?j.css({width:0,height:0}):j.css({width:d.data.width,height:d.data.height}),d.load(b,w),"all"===k.preload&&d.add(c.image)):"empty"===D||"numbers"===D?(d={container:f.create("galleria-image"),image:f.create("img","span"),ready:!0},"numbers"===D&&e(d.image).text(a+
1),this.$("thumbnails").append(d.container),i.setTimeout(y(d.image,a,d.container),50+20*a)):d={container:null,image:null},e(d.container).add(k.keepSource&&k.linkSourceImages?c.original:null).data({index:a,alt:c.description}).bind(k.thumbEventType,t),h===b&&e(d.container).addClass("active"),this._thumbnails.push(d)},_run:function(){var a=this;a._createThumbnails();f.wait({until:function(){g.OPERA&&a.$("stage").css("display","inline-block");a._stageWidth=a.$("stage").width();a._stageHeight=a.$("stage").height();
return a._stageWidth&&50<a._stageHeight},success:function(){a.trigger(g.READY)},error:function(){g.raise("Stage measures not found",!0)}})},load:function(a,b,d){var c=this;this._data=[];this._thumbnails=[];this.$("thumbnails").empty();"function"===typeof b&&(d=b,b=null);a=a||this._options.dataSource;b=b||this._options.dataSelector;d=d||this._options.dataConfig;if(a.constructor===Array)return this.validate(a)?(this._data=a,this._parseData().trigger(g.DATA)):g.raise("Load failed: JSON Array not valid."),
this;e(a).find(b).each(function(a,b){var b=e(b),f={},g=b.parent().attr("href");/\.(png|gif|jpg|jpeg)(\?.*)?$/i.test(g)?f.image=g:g&&(f.link=g);c._data.push(e.extend({title:b.attr("title"),thumb:b.attr("src"),image:b.attr("src"),description:"undefined"==typeof b.attr("alt")?"":b.attr("alt"),link:b.attr("longdesc"),original:b.get(0)},f,d(b)))});this.getDataLength()?this.trigger(g.DATA):g.raise("Load failed: no data found.");return this},_parseData:function(){var a=this;e.each(this._data,function(b,
d){!1==="thumb"in d&&(a._data[b].thumb=d.image)});return this},splice:function(){Array.prototype.splice.apply(this._data,f.array(arguments));return this._parseData()._createThumbnails()},push:function(){Array.prototype.push.apply(this._data,f.array(arguments));return this._parseData()._createThumbnails()},_getActive:function(){return this._controls.getActive()},validate:function(){return!0},bind:function(a,b){a=B(a);this.$("container").bind(a,this.proxy(b));return this},unbind:function(a){a=B(a);
this.$("container").unbind(a);return this},trigger:function(a){a="object"===typeof a?e.extend(a,{scope:this}):{type:B(a),scope:this};this.$("container").trigger(a);return this},addIdleState:function(a,b){this._idle.add.apply(this._idle,f.array(arguments));return this},removeIdleState:function(a){this._idle.remove.apply(this._idle,f.array(arguments));return this},enterIdleMode:function(){this._idle.hide();return this},exitIdleMode:function(){this._idle.showAll();return this},enterFullscreen:function(a){this._fullscreen.enter.apply(this,
f.array(arguments));return this},exitFullscreen:function(a){this._fullscreen.exit.apply(this,f.array(arguments));return this},toggleFullscreen:function(a){this._fullscreen[this.isFullscreen()?"exit":"enter"].apply(this,f.array(arguments));return this},bindTooltip:function(a,b){this._tooltip.bind.apply(this._tooltip,f.array(arguments));return this},defineTooltip:function(a,b){this._tooltip.define.apply(this._tooltip,f.array(arguments));return this},refreshTooltip:function(a){this._tooltip.show.apply(this._tooltip,
f.array(arguments));return this},openLightbox:function(){this._lightbox.show.apply(this._lightbox,f.array(arguments));return this},closeLightbox:function(){this._lightbox.hide.apply(this._lightbox,f.array(arguments));return this},getActiveImage:function(){return this._getActive().image||void 0},getActiveThumb:function(){return this._thumbnails[this._active].image||void 0},getMousePosition:function(a){return{x:a.pageX-this.$("container").offset().left,y:a.pageY-this.$("container").offset().top}},addPan:function(a){if(!1!==
this._options.imageCrop){var a=e(a||this.getActiveImage()),b=this,d=a.width()/2,c=a.height()/2,g=parseInt(a.css("left"),10),l=parseInt(a.css("top"),10),k=g||0,h=l||0,i=0,m=0,y=!1,t=f.timestamp(),w=0,p=0,H=function(b,c,d){if(0<b&&(p=Math.round(Math.max(-1*b,Math.min(0,c))),w!==p))if(w=p,8===n)a.parent()["scroll"+d](-1*p);else b={},b[d.toLowerCase()]=p,a.css(b)},q=function(a){50>f.timestamp()-t||(y=!0,d=b.getMousePosition(a).x,c=b.getMousePosition(a).y)};8===n&&(a.parent().scrollTop(-1*h).scrollLeft(-1*
k),a.css({top:0,left:0}));this.$("stage").unbind("mousemove",q).bind("mousemove",q);f.addTimer("pan",function(){y&&(i=a.width()-b._stageWidth,m=a.height()-b._stageHeight,g=-1*d/b._stageWidth*i,l=-1*c/b._stageHeight*m,k+=(g-k)/b._options.imagePanSmoothness,h+=(l-h)/b._options.imagePanSmoothness,H(m,h,"Top"),H(i,k,"Left"))},50,!0);return this}},proxy:function(a,b){if("function"!==typeof a)return function(){};b=b||this;return function(){return a.apply(b,f.array(arguments))}},removePan:function(){this.$("stage").unbind("mousemove");
f.clearTimer("pan");return this},addElement:function(a){var b=this._dom;e.each(f.array(arguments),function(a,c){b[c]=f.create("galleria-"+c)});return this},attachKeyboard:function(a){this._keyboard.attach.apply(this._keyboard,f.array(arguments));return this},detachKeyboard:function(){this._keyboard.detach.apply(this._keyboard,f.array(arguments));return this},appendChild:function(a,b){this.$(a).append(this.get(b)||b);return this},prependChild:function(a,b){this.$(a).prepend(this.get(b)||b);return this},
remove:function(a){this.$(f.array(arguments).join(",")).remove();return this},append:function(a){var b,d;for(b in a)if(a.hasOwnProperty(b))if(a[b].constructor===Array)for(d=0;a[b][d];d++)this.appendChild(b,a[b][d]);else this.appendChild(b,a[b]);return this},_scaleImage:function(a,b){b=e.extend({width:this._stageWidth,height:this._stageHeight,crop:this._options.imageCrop,max:this._options.maxScaleRatio,min:this._options.minScaleRatio,margin:this._options.imageMargin,position:this._options.imagePosition},
b);(a||this._controls.getActive()).scale(b);return this},updateCarousel:function(){this._carousel.update();return this},rescale:function(a,b,d){var c=this;"function"===typeof a&&(d=a,a=void 0);var e=function(){c._stageWidth=a||c.$("stage").width();c._stageHeight=b||c.$("stage").height();c._scaleImage();c._options.carousel&&c.updateCarousel();c.trigger(g.RESCALE);"function"===typeof d&&d.call(c)};g.WEBKIT&&!a&&!b?f.addTimer("scale",e,5):e.call(c);return this},refreshImage:function(){this._scaleImage();
this._options.imagePan&&this.addPan();return this},show:function(a,b,d){if(!(!1===a||!this._options.queue&&this._queue.stalled))if(a=Math.max(0,Math.min(parseInt(a,10),this.getDataLength()-1)),b="undefined"!==typeof b?!!b:a<this.getIndex(),!d&&g.History)g.History.value(a.toString());else return this._active=a,Array.prototype.push.call(this._queue,{index:a,rewind:b}),this._queue.stalled||this._show(),this},_show:function(){var a=this,b=this._queue[0],d=this.getData(b.index);if(d){var c=d.image,j=this._controls.getActive(),
l=this._controls.getNext(),k=l.isCached(c),h=this._thumbnails[b.index],m=function(){a._queue.stalled=!1;f.toggleQuality(l.image,a._options.imageQuality);e(j.container).css({zIndex:0,opacity:0});e(l.container).css({zIndex:1,opacity:1});a._controls.swap();a._options.imagePan&&a.addPan(l.image);d.link&&e(l.image).css({cursor:"pointer"}).bind(q(),function(){a._options.popupLinks?i.open(d.link,"_blank"):i.location.href=d.link});Array.prototype.shift.call(a._queue);a._queue.length&&a._show();a._playCheck();
a.trigger({type:g.IMAGE,index:b.index,imageTarget:l.image,thumbTarget:h.image})};this._options.carousel&&this._options.carouselFollow&&this._carousel.follow(b.index);if(this._options.preload){var n,p,t=this.getNext();try{for(p=this._options.preload;0<p;p--)n=new g.Picture,n.add(a.getData(t).image),t=a.getNext(t)}catch(w){}}f.show(l.container);e(a._thumbnails[b.index].container).addClass("active").siblings(".active").removeClass("active");a.trigger({type:g.LOADSTART,cached:k,index:b.index,imageTarget:l.image,
thumbTarget:h.image});l.load(c,function(c){a._scaleImage(c,{complete:function(c){f.show(c.container);"image"in j&&f.toggleQuality(j.image,!1);f.toggleQuality(c.image,!1);a._queue.stalled=!0;a.removePan();a.setInfo(b.index);a.setCounter(b.index);a.trigger({type:g.LOADFINISH,cached:k,index:b.index,imageTarget:c.image,thumbTarget:a._thumbnails[b.index].image});var d=null===j.image&&a._options.transitionInitial?a._options.transition_Initial:a._options.transition;!1===d in C?m():C[d].call(a,{prev:j.image,
next:c.image,rewind:b.rewind,speed:a._options.transitionSpeed||400},m)}})});e(l.image).attr("alt",d.description)}},getNext:function(a){a="number"===typeof a?a:this.getIndex();return a===this.getDataLength()-1?0:a+1},getPrev:function(a){a="number"===typeof a?a:this.getIndex();return 0===a?this.getDataLength()-1:a-1},next:function(){1<this.getDataLength()&&this.show(this.getNext(),!1);return this},prev:function(){1<this.getDataLength()&&this.show(this.getPrev(),!0);return this},get:function(a){return a in
this._dom?this._dom[a]:null},getData:function(a){return a in this._data?this._data[a]:this._data[this._active]},getDataLength:function(){return this._data.length},getIndex:function(){return"number"===typeof this._active?this._active:!1},getStageHeight:function(){return this._stageHeight},getStageWidth:function(){return this._stageWidth},getOptions:function(a){return"undefined"===typeof a?this._options:this._options[a]},setOptions:function(a,b){"object"===typeof a?e.extend(this._options,a):this._options[a]=
b;return this},play:function(a){this._playing=!0;this._playtime=a||this._playtime;this._playCheck();this.trigger(g.PLAY);return this},pause:function(){this._playing=!1;this.trigger(g.PAUSE);return this},playToggle:function(a){return this._playing?this.pause():this.play(a)},isPlaying:function(){return this._playing},isFullscreen:function(){return this._fullscreen.active},_playCheck:function(){var a=this,b=0,d=f.timestamp(),c="play"+this._id;if(this._playing){f.clearTimer(c);var e=function(){b=f.timestamp()-
d;b>=a._playtime&&a._playing?(f.clearTimer(c),a.next()):a._playing&&(a.trigger({type:g.PROGRESS,percent:Math.ceil(100*(b/a._playtime)),seconds:Math.floor(b/1E3),milliseconds:b}),f.addTimer(c,e,20))};f.addTimer(c,e,20)}},setIndex:function(a){this._active=a;return this},setCounter:function(a){"number"===typeof a?a++:"undefined"===typeof a&&(a=this.getIndex()+1);this.get("current").innerHTML=a;if(n){var a=this.$("counter"),b=a.css("opacity"),d=a.attr("style");1===b?a.attr("style",d.replace(/filter[^\;]+\;/i,
"")):this.$("counter").css("opacity",b)}return this},setInfo:function(a){var b=this,d=this.getData(a);e.each(["title","description","author"],function(a,e){var f=b.$("info-"+e);d[e]?f[d[e].length?"show":"hide"]().html(d[e]):f.empty().hide()});return this},hasInfo:function(a){var b=["title","description"],d;for(d=0;b[d];d++)if(this.getData(a)[b[d]])return!0;return!1},jQuery:function(a){var b=this,d=[];e.each(a.split(","),function(a,c){c=e.trim(c);b.get(c)&&d.push(c)});var c=e(b.get(d.shift()));e.each(d,
function(a,d){c=c.add(b.get(d))});return c},$:function(a){return this.jQuery.apply(this,f.array(arguments))}};e.each(x,function(a,b){var d=/_/.test(b)?b.replace(/_/g,""):b;g[b.toUpperCase()]="galleria."+d});e.extend(g,{IE9:9===n,IE8:8===n,IE7:7===n,IE6:6===n,IE:!!n,WEBKIT:/webkit/.test(p),SAFARI:/safari/.test(p),CHROME:/chrome/.test(p),QUIRK:n&&m.compatMode&&"BackCompat"===m.compatMode,MAC:/mac/.test(navigator.platform.toLowerCase()),OPERA:!!i.opera,IPHONE:/iphone/.test(p),IPAD:/ipad/.test(p),ANDROID:/android/.test(p),
TOUCH:!(!/iphone/.test(p)&&!/ipad/.test(p)&&!/android/.test(p))});g.addTheme=function(a){a.name||g.raise("No theme name specified");a.defaults="object"!==typeof a.defaults?{}:G(a.defaults);var b=!1,d;"string"===typeof a.css?(e("link").each(function(c,e){d=RegExp(a.css);if(d.test(e.href))return b=!0,g.theme=a,u.trigger(g.THEMELOAD),!1}),b||e("script").each(function(c,e){d=RegExp("galleria\\."+a.name.toLowerCase()+"\\.");d.test(e.src)&&(b=e.src.replace(/[^\/]*$/,"")+a.css,f.addTimer("css",function(){f.loadCSS(b,
"galleria-theme",function(){g.theme=a;u.trigger(g.THEMELOAD)})},1))}),b||g.raise("No theme CSS loaded")):(g.theme=a,u.trigger(g.THEMELOAD));return a};g.loadTheme=function(a,b){var d=!1,c=v.length;g.theme=void 0;f.loadScript(a,function(){d=!0});f.wait({until:function(){return d},error:function(){g.raise("Theme at "+a+" could not load, check theme path.",!0)},success:function(){if(c){var a=[];e.each(g.get(),function(c,d){var f=e.extend(d._original.options,{data_source:d._data},b);d.$("container").remove();
var i=new g;i._id=d._id;i.init(d._original.target,f);a.push(i)});v=a}},timeout:2E3})};g.get=function(a){if(v[a])return v[a];if("number"!==typeof a)return v;g.raise("Gallery index "+a+" not found")};g.addTransition=function(a,b){C[a]=b};g.utils=f;g.log=function(){try{i.console.log.apply(i.console,f.array(arguments))}catch(a){try{i.opera.postError.apply(i.opera,arguments)}catch(b){i.alert(f.array(arguments).split(", "))}}};g.raise=function(a,b){if(z||b)throw Error((b?"Fatal error":"Error")+": "+a);
};g.Picture=function(a){this.id=a||null;this.image=null;this.container=f.create("galleria-image");e(this.container).css({overflow:"hidden",position:"relative"});this.original={width:0,height:0};this.loaded=this.ready=!1};g.Picture.prototype={cache:{},add:function(a){var b,d=this,c=new Image,f=function(){if((!this.width||!this.height)&&1E3>b)b++,e(c).load(f).attr("src",a+"?"+(new Date).getTime());d.original={height:this.height,width:this.width};d.cache[a]=a;d.loaded=!0};e(c).css("display","block");
if(d.cache[a])return c.src=a,f.call(c),c;e(c).load(f).attr("src",a);return c},show:function(){f.show(this.image)},hide:function(){f.moveOut(this.image)},clear:function(){this.image=null},isCached:function(a){return!!this.cache[a]},load:function(a,b){var d=this;e(this.container).empty(!0);this.image=this.add(a);f.hide(this.image);e(this.container).append(this.image);f.wait({until:function(){return d.loaded&&d.image.complete&&d.original.width&&d.image.width},success:function(){i.setTimeout(function(){b.call(d,
d)},50)},error:function(){i.setTimeout(function(){b.call(d,d)},50);g.raise("image not loaded in 10 seconds: "+a)},timeout:1E4});return this.container},scale:function(a){a=e.extend({width:0,height:0,min:void 0,max:void 0,margin:0,complete:function(){},position:"center",crop:!1},a);if(!this.image)return this.container;var b,d,c=this,j=e(c.container);f.wait({until:function(){b=a.width||j.width()||f.parseValue(j.css("width"));d=a.height||j.height()||f.parseValue(j.css("height"));return b&&d},success:function(){var g=
(b-2*a.margin)/c.original.width,j=(d-2*a.margin)/c.original.height,h={"true":Math.max(g,j),width:g,height:j,"false":Math.min(g,j)}[a.crop.toString()];a.max&&(h=Math.min(a.max,h));a.min&&(h=Math.max(a.min,h));e(c.container).width(b).height(d);e.each(["width","height"],function(a,b){e(c.image)[b](c.image[b]=c[b]=Math.round(c.original[b]*h))});var i={},m={},g=function(a,b,d){var g=0;/\%/.test(a)?(a=parseInt(a,10)/100,b=c.image[b]||e(c.image)[b](),g=Math.ceil(-1*b*a+d*a)):g=f.parseValue(a);return g},
n={top:{top:0},left:{left:0},right:{left:"100%"},bottom:{top:"100%"}};e.each(a.position.toLowerCase().split(" "),function(a,b){"center"===b&&(b="50%");i[a?"top":"left"]=b});e.each(i,function(a,b){n.hasOwnProperty(b)&&e.extend(m,n[b])});i=i.top?e.extend(i,m):m;i=e.extend({top:"50%",left:"50%"},i);e(c.image).css({position:"relative",top:g(i.top,"height",d),left:g(i.left,"width",b)});c.show();c.ready=!0;a.complete.call(c,c)},error:function(){g.raise("Could not scale image: "+c.image.src)},timeout:1E3});
return this}};e.extend(e.easing,{galleria:function(a,b,d,c,e){return 1>(b/=e/2)?c/2*b*b*b*b+d:-c/2*((b-=2)*b*b*b-2)+d},galleriaIn:function(a,b,d,c,e){return c*(b/=e)*b*b*b+d},galleriaOut:function(a,b,d,c,e){return-c*((b=b/e-1)*b*b*b-1)+d}});e.fn.galleria=function(a){return this.each(function(){(new g).init(this,a)})};i.Galleria=g})(jQuery);