/*
* qTip2 - Pretty powerful tooltips
* http://craigsworks.com/projects/qtip2/
*
* Version: 2.0.0pre
* Copyright 2009-2010 Craig Michael Thompson - http://craigsworks.com
*
* Dual licensed under MIT or GPLv2 licenses
*   http://en.wikipedia.org/wiki/MIT_License
*   http://en.wikipedia.org/wiki/GNU_General_Public_License
*
* Date: Mon Apr 9 17:49:18 2012 +0100
*/
(function(b){"function"===typeof define&&define.amd?define(["jquery"],b):b(jQuery)})(function(b){function P(){P.history=P.history||[];P.history.push(arguments);if("object"===typeof console){var b=console[console.warn?"warn":"log"],a=Array.prototype.slice.call(arguments);"string"===typeof arguments[0]&&(a[0]="qTip2: "+a[0]);b.apply?b.apply(console,a):b(a)}}function R(d){var a;if(!d||"object"!==typeof d)return h;if(d.metadata===C||"object"!==typeof d.metadata)d.metadata={type:d.metadata};if("content"in
d){if(d.content===C||"object"!==typeof d.content||d.content.jquery)d.content={text:d.content};a=d.content.text||h;if(!b.isFunction(a)&&(!a&&!a.attr||1>a.length||"object"===typeof a&&!a.jquery))d.content.text=h;if("title"in d.content){if(d.content.title===C||"object"!==typeof d.content.title)d.content.title={text:d.content.title};a=d.content.title.text||h;if(!b.isFunction(a)&&(!a&&!a.attr||1>a.length||"object"===typeof a&&!a.jquery))d.content.title.text=h}}if("position"in d&&(d.position===C||"object"!==
typeof d.position))d.position={my:d.position,at:d.position};if("show"in d&&(d.show===C||"object"!==typeof d.show))d.show=d.show.jquery?{target:d.show}:{event:d.show};if("hide"in d&&(d.hide===C||"object"!==typeof d.hide))d.hide=d.hide.jquery?{target:d.hide}:{event:d.hide};if("style"in d&&(d.style===C||"object"!==typeof d.style))d.style={classes:d.style};b.each(D,function(){this.sanitize&&this.sanitize(d)});return d}function X(d,a,s,v){function i(c){for(var b=0,f,e=a,c=c.split(".");e=e[c[b++]];)b<c.length&&
(f=e);return[f||a,c.pop()]}function r(){var c=a.style.widget;f.toggleClass(U,c).toggleClass(W,a.style.def&&!c);k.content.toggleClass(U+"-content",c);k.titlebar&&k.titlebar.toggleClass(U+"-header",c);k.button&&k.button.toggleClass(A+"-icon",!c)}function q(c){k.title&&(k.titlebar.remove(),k.titlebar=k.title=k.button=C,c!==h&&e.reposition())}function t(){var c=a.content.title.button,d="string"===typeof c?c:"Close tooltip";k.button&&k.button.remove();k.button=c.jquery?c:b("<a />",{"class":"ui-state-default ui-tooltip-close "+
(a.style.widget?"":A+"-icon"),title:d,"aria-label":d}).prepend(b("<span />",{"class":"ui-icon ui-icon-close",html:"&times;"}));k.button.appendTo(k.titlebar).attr("role","button").click(function(c){f.hasClass(J)||e.hide(c);return h});e.redraw()}function y(){var c=w+"-title";k.titlebar&&q();k.titlebar=b("<div />",{"class":A+"-titlebar "+(a.style.widget?"ui-widget-header":"")}).append(k.title=b("<div />",{id:c,"class":A+"-title","aria-atomic":p})).insertBefore(k.content).delegate(".ui-tooltip-close",
"mousedown keydown mouseup keyup mouseout",function(c){b(this).toggleClass("ui-state-active ui-state-focus","down"===c.type.substr(-4))}).delegate(".ui-tooltip-close","mouseover mouseout",function(c){b(this).toggleClass("ui-state-hover","mouseover"===c.type)});a.content.title.button?t():e.rendered&&e.redraw()}function M(c,a){var x=k.title;if(!e.rendered||!c)return h;b.isFunction(c)&&(c=c.call(d,z.event,e));if(c===h||!c&&""!==c)return q(h);c.jquery&&0<c.length?x.empty().append(c.css({display:"block"})):
x.html(c);e.redraw();a!==h&&(e.rendered&&0<f[0].offsetWidth)&&e.reposition(z.event)}function n(c,a){function x(c){function f(d){d&&(delete x[d.src],clearTimeout(e.timers.img[d.src]),b(d).unbind(g));b.isEmptyObject(x)&&(e.redraw(),a!==h&&e.reposition(z.event),c())}var d,x={};if(0===(d=u.find("img[src]:not([height]):not([width])")).length)return f();d.each(function(c,a){if(x[a.src]===K){var d=0;(function Y(){if(a.height||a.width||3<d)return f(a);d+=1;e.timers.img[a.src]=setTimeout(Y,700)})();b(a).bind("error"+
g+" load"+g,function(){f(this)});x[a.src]=a}})}var u=k.content;if(!e.rendered||!c)return h;b.isFunction(c)&&(c=c.call(d,z.event,e)||"");c.jquery&&0<c.length?u.empty().append(c.css({display:"block"})):u.html(c);0>e.rendered?f.queue("fx",x):(m=0,x(b.noop));return e}function H(){function c(c){if(f.hasClass(J))return h;clearTimeout(e.timers.show);clearTimeout(e.timers.hide);var b=function(){e.toggle(p,c)};0<a.show.delay?e.timers.show=setTimeout(b,a.show.delay):b()}function G(c){if(f.hasClass(J)||I||m)return h;
var d=b(c.relatedTarget||c.target),x=d.closest(Q)[0]===f[0],d=d[0]===F.show[0];clearTimeout(e.timers.show);clearTimeout(e.timers.hide);if("mouse"===w.target&&x||a.hide.fixed&&/mouse(out|leave|move)/.test(c.type)&&(x||d))try{c.preventDefault(),c.stopImmediatePropagation()}catch(G){}else 0<a.hide.delay?e.timers.hide=setTimeout(function(){e.hide(c)},a.hide.delay):e.hide(c)}function x(c){if(f.hasClass(J))return h;clearTimeout(e.timers.inactive);e.timers.inactive=setTimeout(function(){e.hide(c)},a.hide.inactive)}
function u(c){e.rendered&&0<f[0].offsetWidth&&e.reposition(c)}var w=a.position,F={show:a.show.target,hide:a.hide.target,viewport:b(w.viewport),document:b(document),body:b(document.body),window:b(window)},i=b.trim(""+a.show.event).split(" "),j=b.trim(""+a.hide.event).split(" "),q=b.browser.msie&&6===parseInt(b.browser.version,10);f.bind("mouseenter"+g+" mouseleave"+g,function(c){var b="mouseenter"===c.type;b&&e.focus(c);f.toggleClass(Z,b)});a.hide.fixed&&(F.hide=F.hide.add(f),f.bind("mouseover"+g,
function(){f.hasClass(J)||clearTimeout(e.timers.hide)}));/mouse(out|leave)/i.test(a.hide.event)?"window"===a.hide.leave&&F.window.bind("mouseout"+g+" blur"+g,function(c){/select|option/.test(c.target)&&!c.relatedTarget&&e.hide(c)}):/mouse(over|enter)/i.test(a.show.event)&&F.hide.bind("mouseleave"+g,function(){clearTimeout(e.timers.show)});-1<(""+a.hide.event).indexOf("unfocus")&&w.container.closest("html").bind("mousedown"+g,function(c){var a=b(c.target);e.rendered&&f.hasClass(J);var x=0<a.parents(Q).filter(f[0]).length;
a[0]!==d[0]&&(a[0]!==f[0]&&!x&&!d.has(a[0]).length&&!a.attr("disabled"))&&e.hide(c)});"number"===typeof a.hide.inactive&&(F.show.bind("qtip-"+s+"-inactive",x),b.each(B.inactiveEvents,function(c,b){F.hide.add(k.tooltip).bind(b+g+"-inactive",x)}));b.each(j,function(a,d){var e=b.inArray(d,i),x=b(F.hide);-1<e&&x.add(F.show).length===x.length||"unfocus"===d?(F.show.bind(d+g,function(b){0<f[0].offsetWidth?G(b):c(b)}),delete i[e]):F.hide.bind(d+g,G)});b.each(i,function(b,a){F.show.bind(a+g,c)});"number"===
typeof a.hide.distance&&F.show.add(f).bind("mousemove"+g,function(c){var b=z.origin||{},d=a.hide.distance,f=Math.abs;(f(c.pageX-b.pageX)>=d||f(c.pageY-b.pageY)>=d)&&e.hide(c)});"mouse"===w.target&&(F.show.bind("mousemove"+g,function(c){L={pageX:c.pageX,pageY:c.pageY,type:"mousemove"}}),w.adjust.mouse&&(a.hide.event&&(f.bind("mouseleave"+g,function(c){(c.relatedTarget||c.target)!==F.show[0]&&e.hide(c)}),k.target.bind("mouseenter"+g+" mouseleave"+g,function(c){z.onTarget="mouseenter"===c.type})),F.document.bind("mousemove"+
g,function(c){e.rendered&&(z.onTarget&&!f.hasClass(J)&&0<f[0].offsetWidth)&&e.reposition(c||L)})));if(w.adjust.resize||F.viewport.length)(b.event.special.resize?F.viewport:F.window).bind("resize"+g,u);(F.viewport.length||q&&"fixed"===f.css("position"))&&F.viewport.bind("scroll"+g,u)}function j(){var c=[a.show.target[0],a.hide.target[0],e.rendered&&k.tooltip[0],a.position.container[0],a.position.viewport[0],window,document];e.rendered?b([]).pushStack(b.grep(c,function(c){return"object"===typeof c})).unbind(g):
a.show.target.unbind(g+"-create")}var e=this,u=document.body,w=A+"-"+s,I=0,m=0,f=b(),g=".qtip-"+s,k,z;e.id=s;e.rendered=h;e.elements=k={target:d};e.timers={img:{}};e.options=a;e.checks={};e.plugins={};e.cache=z={event:{},target:b(),disabled:h,attr:v,onTarget:h};e.checks.builtin={"^id$":function(c,a,d){c=d===p?B.nextid:d;a=A+"-"+c;c!==h&&(0<c.length&&!b("#"+a).length)&&(f[0].id=a,k.content[0].id=a+"-content",k.title[0].id=a+"-title")},"^content.text$":function(c,b,a){n(a)},"^content.title.text$":function(c,
b,a){if(!a)return q();!k.title&&a&&y();M(a)},"^content.title.button$":function(c,a,b){c=k.button;a=k.title;e.rendered&&(b?(a||y(),t()):c.remove())},"^position.(my|at)$":function(c,a,b){"string"===typeof b&&(c[a]=new D.Corner(b))},"^position.container$":function(c,a,b){e.rendered&&f.appendTo(b)},"^show.ready$":function(){e.rendered?e.toggle(p):e.render(1)},"^style.classes$":function(c,a,b){f.attr("class",A+" qtip ui-helper-reset "+b)},"^style.widget|content.title":r,"^events.(render|show|move|hide|focus|blur)$":function(c,
a,d){f[(b.isFunction(d)?"":"un")+"bind"]("tooltip"+a,d)},"^(show|hide|position).(event|target|fixed|inactive|leave|distance|viewport|adjust)":function(){var c=a.position;f.attr("tracking","mouse"===c.target&&c.adjust.mouse);j();H()}};b.extend(e,{render:function(c){if(e.rendered)return e;var u=a.content.text,x=a.content.title.text,g=a.position,i=b.Event("tooltiprender");b.attr(d[0],"aria-describedby",w);f=k.tooltip=b("<div/>",{id:w,"class":A+" qtip ui-helper-reset "+W+" "+a.style.classes+" "+A+"-pos-"+
a.position.my.abbrev(),width:a.style.width||"",height:a.style.height||"",tracking:"mouse"===g.target&&g.adjust.mouse,role:"alert","aria-live":"polite","aria-atomic":h,"aria-describedby":w+"-content","aria-hidden":p}).toggleClass(J,z.disabled).data("qtip",e).appendTo(a.position.container).append(k.content=b("<div />",{"class":A+"-content",id:w+"-content","aria-atomic":p}));e.rendered=-1;I=m=1;x&&(y(),b.isFunction(x)||M(x,h));b.isFunction(u)||n(u,h);e.rendered=p;r();b.each(a.events,function(c,a){b.isFunction(a)&&
f.bind("toggle"===c?"tooltipshow tooltiphide":"tooltip"+c,a)});b.each(D,function(){"render"===this.initialize&&this(e)});H();f.queue("fx",function(b){i.originalEvent=z.event;f.trigger(i,[e]);I=m=0;e.redraw();(a.show.ready||c)&&e.toggle(p,z.event,h);b()});return e},get:function(c){switch(c.toLowerCase()){case "dimensions":c={height:f.outerHeight(),width:f.outerWidth()};break;case "offset":c=D.offset(f,a.position.container);break;default:c=i(c.toLowerCase()),c=c[0][c[1]],c=c.precedance?c.string():c}return c},
set:function(c,d){var u=/^position\.(my|at|adjust|target|container)|style|content|show\.ready/i,k=/^content\.(title|attr)|style/i,w=h,g=h,s=e.checks,j;"string"===typeof c?(j=c,c={},c[j]=d):c=b.extend(p,{},c);b.each(c,function(a,d){var f=i(a.toLowerCase()),e;e=f[0][f[1]];f[0][f[1]]="object"===typeof d&&d.nodeType?b(d):d;c[a]=[f[0],f[1],d,e];w=u.test(a)||w;g=k.test(a)||g});R(a);I=m=1;b.each(c,function(c,a){var b,d,f;for(b in s)for(d in s[b])if(f=RegExp(d,"i").exec(c))a.push(f),s[b][d].apply(e,a)});
I=m=0;e.rendered&&0<f[0].offsetWidth&&(w&&e.reposition("mouse"===a.position.target?C:z.event),g&&e.redraw());return e},toggle:function(c,d,u){function k(){c?(b.browser.msie&&f[0].style.removeAttribute("filter"),f.css("overflow",""),"string"===typeof g.autofocus&&b(g.autofocus,f).focus(),g.target.trigger("qtip-"+s+"-inactive")):f.css({display:"",visibility:"",opacity:"",left:"",top:""});r=b.Event("tooltip"+(c?"visible":"hidden"));r.originalEvent=d?z.event:C;f.trigger(r,[e])}if(!e.rendered)return c?
e.render(1):e;var w=c?"show":"hide",g=a[w],i=a.position,m=a.content,I=0<f[0].offsetWidth,j=c||1===g.target.length,q=!d||2>g.target.length||z.target[0]===d.target,r;(typeof c).search("boolean|number")&&(c=!I);if(!f.is(":animated")&&I===c&&q)return e;if(d){if(/over|enter/.test(d.type)&&/out|leave/.test(z.event.type)&&a.show.target.add(d.target).length===a.show.target.length&&f.has(d.relatedTarget).length)return e;z.event=b.extend({},d)}r=b.Event("tooltip"+w);r.originalEvent=d?z.event:C;f.trigger(r,
[e,90]);if(r.isDefaultPrevented())return e;b.attr(f[0],"aria-hidden",!c);c?(z.origin=b.extend({},L),e.focus(d),b.isFunction(m.text)&&n(m.text,h),b.isFunction(m.title.text)&&M(m.title.text,h),!S&&("mouse"===i.target&&i.adjust.mouse)&&(b(document).bind("mousemove.qtip",function(c){L={pageX:c.pageX,pageY:c.pageY,type:"mousemove"}}),S=p),e.reposition(d,u),(r.solo=!!g.solo)&&b(Q,g.solo).not(f).qtip("hide",r)):(clearTimeout(e.timers.show),delete z.origin,S&&!b(Q+'[tracking="true"]:visible',g.solo).not(f).length&&
(b(document).unbind("mousemove.qtip"),S=h),e.blur(d));g.effect===h||j===h?(f[w](),k.call(f)):b.isFunction(g.effect)?(f.stop(1,1),g.effect.call(f,e),f.queue("fx",function(c){k();c()})):f.fadeTo(90,c?1:0,k);c&&g.target.trigger("qtip-"+s+"-inactive");return e},show:function(c){return e.toggle(p,c)},hide:function(c){return e.toggle(h,c)},focus:function(c){if(!e.rendered)return e;var a=b(Q),d=parseInt(f[0].style.zIndex,10),u=B.zindex+a.length,c=b.extend({},c),g;f.hasClass(T)||(g=b.Event("tooltipfocus"),
g.originalEvent=c,f.trigger(g,[e,u]),g.isDefaultPrevented()||(d!==u&&(a.each(function(){this.style.zIndex>d&&(this.style.zIndex-=1)}),a.filter("."+T).qtip("blur",c)),f.addClass(T)[0].style.zIndex=u));return e},blur:function(c){var c=b.extend({},c),a;f.removeClass(T);a=b.Event("tooltipblur");a.originalEvent=c;f.trigger(a,[e]);return e},reposition:function(c,d){if(!e.rendered||I)return e;I=1;var g=a.position.target,w=a.position,i=w.my,m=w.at,s=w.adjust,j=s.method.split(" "),q=f.outerWidth(),r=f.outerHeight(),
p=0,y=0,t=b.Event("tooltipmove"),C="fixed"===f.css("position"),n=w.viewport,l={left:0,top:0},v=w.container,M=h,E=e.plugins.tip,H=0<f[0].offsetWidth,B={horizontal:j[0],vertical:j[1]=j[1]||j[0],enabled:n.jquery&&g[0]!==window&&g[0]!==u&&"none"!==s.method,left:function(c){var a="shift"===B.horizontal,d=-v.offset.left+n.offset.left+n.scrollLeft,b="left"===i.x?q:"right"===i.x?-q:-q/2,f="left"===m.x?p:"right"===m.x?-p:-p/2,e=E&&E.size?E.size.width||0:0,g=E&&E.corner&&"x"===E.corner.precedance&&!a?e:0,u=
d-c+g,w=c+q-n.width-d+g,f=b-("x"===i.precedance||i.x===i.y?f:0)-("center"===m.x?p/2:0),g="center"===i.x;if(a)g=E&&E.corner&&"y"===E.corner.precedance?e:0,f=("left"===i.x?1:-1)*b-g,l.left+=0<u?u:0<w?-w:0,l.left=Math.max(-v.offset.left+n.offset.left+(g&&"center"===E.corner.x?E.offset:0),c-f,Math.min(Math.max(-v.offset.left+n.offset.left+n.width,c+f),l.left));else{if(0<u&&("left"!==i.x||0<w))l.left-=f;else if(0<w&&("right"!==i.x||0<u))l.left-=g?-f:f;l.left!==c&&g&&(l.left-=s.x);l.left<d&&-l.left>w&&
(l.left=c)}return l.left-c},top:function(c){var a="shift"===B.vertical,d=-v.offset.top+n.offset.top+n.scrollTop,b="top"===i.y?r:"bottom"===i.y?-r:-r/2,f="top"===m.y?y:"bottom"===m.y?-y:-y/2,e=E&&E.size?E.size.height||0:0,g=E&&E.corner&&"y"===E.corner.precedance&&!a?e:0,u=d-c+g,d=c+r-n.height-d+g,f=b-("y"===i.precedance||i.x===i.y?f:0)-("center"===m.y?y/2:0),g="center"===i.y;if(a)g=E&&E.corner&&"x"===E.corner.precedance?e:0,f=("top"===i.y?1:-1)*b-g,l.top+=0<u?u:0<d?-d:0,l.top=Math.max(-v.offset.top+
n.offset.top+(g&&"center"===E.corner.x?E.offset:0),c-f,Math.min(Math.max(-v.offset.top+n.offset.top+n.height,c+f),l.top));else{if(0<u&&("top"!==i.y||0<d))l.top-=f;else if(0<d&&("bottom"!==i.y||0<u))l.top-=g?-f:f;l.top!==c&&g&&(l.top-=s.y);0>l.top&&-l.top>d&&(l.top=c)}return l.top-c}};if(b.isArray(g)&&2===g.length)m={x:"left",y:"top"},l={left:g[0],top:g[1]};else if("mouse"===g&&(c&&c.pageX||z.event.pageX))m={x:"left",y:"top"},c=(c&&("resize"===c.type||"scroll"===c.type)?z.event:c&&c.pageX&&"mousemove"===
c.type?c:L&&L.pageX&&(s.mouse||!c||!c.pageX)?{pageX:L.pageX,pageY:L.pageY}:!s.mouse&&z.origin&&z.origin.pageX&&a.show.distance?z.origin:c)||c||z.event||L||{},l={top:c.pageY,left:c.pageX};else{g="event"===g?c&&c.target&&"scroll"!==c.type&&"resize"!==c.type?z.target=b(c.target):z.target:z.target=b(g.jquery?g:k.target);g=b(g).eq(0);if(0===g.length)return e;g[0]===document||g[0]===window?(p=D.iOS?window.innerWidth:g.width(),y=D.iOS?window.innerHeight:g.height(),g[0]===window&&(l={top:(n||g).scrollTop(),
left:(n||g).scrollLeft()})):g.is("area")&&D.imagemap?l=D.imagemap(g,m,B.enabled?j:h):"http://www.w3.org/2000/svg"===g[0].namespaceURI&&D.svg?l=D.svg(g,m):(p=g.outerWidth(),y=g.outerHeight(),l=D.offset(g,v));l.offset&&(p=l.width,y=l.height,M=l.flipoffset,l=l.offset);if(4.1>D.iOS&&3.1<D.iOS||4.3==D.iOS||!D.iOS&&C)j=b(window),l.left-=j.scrollLeft(),l.top-=j.scrollTop();l.left+="right"===m.x?p:"center"===m.x?p/2:0;l.top+="bottom"===m.y?y:"center"===m.y?y/2:0}l.left+=s.x+("right"===i.x?-q:"center"===i.x?
-q/2:0);l.top+=s.y+("bottom"===i.y?-r:"center"===i.y?-r/2:0);B.enabled?(n={elem:n,height:n[(n[0]===window?"h":"outerH")+"eight"](),width:n[(n[0]===window?"w":"outerW")+"idth"](),scrollLeft:C?0:n.scrollLeft(),scrollTop:C?0:n.scrollTop(),offset:n.offset()||{left:0,top:0}},v={elem:v,scrollLeft:v.scrollLeft(),scrollTop:v.scrollTop(),offset:v.offset()||{left:0,top:0}},l.adjusted={left:"none"!==B.horizontal?B.left(l.left):0,top:"none"!==B.vertical?B.top(l.top):0},l.adjusted.left+l.adjusted.top&&f.attr("class",
f[0].className.replace(/ui-tooltip-pos-\w+/i,A+"-pos-"+i.abbrev())),M&&l.adjusted.left&&(l.left+=M.left),M&&l.adjusted.top&&(l.top+=M.top)):l.adjusted={left:0,top:0};t.originalEvent=b.extend({},c);f.trigger(t,[e,l,n.elem||n]);if(t.isDefaultPrevented())return e;delete l.adjusted;d===h||!H||isNaN(l.left)||isNaN(l.top)||"mouse"===g||!b.isFunction(w.effect)?f.css(l):b.isFunction(w.effect)&&(w.effect.call(f,e,b.extend({},l)),f.queue(function(c){b(this).css({opacity:"",height:""});b.browser.msie&&this.style.removeAttribute("filter");
c()}));I=0;return e},redraw:function(){if(1>e.rendered||m)return e;var c=a.position.container,d,b,g;m=1;a.style.height&&f.css("height",a.style.height);a.style.width?f.css("width",a.style.width):(f.css("width","").addClass(O),d=f.width()+1,b=f.css("max-width")||"",g=f.css("min-width")||"",c=-1<(b+g).indexOf("%")?c.width()/100:0,b=(-1<b.indexOf("%")?c:1)*parseInt(b,10)||d,g=(-1<g.indexOf("%")?c:1)*parseInt(g,10)||0,d=b+g?Math.min(Math.max(d,g),b):d,f.css("width",Math.round(d)).removeClass(O));m=0;return e},
disable:function(c){"boolean"!==typeof c&&(c=!(f.hasClass(J)||z.disabled));e.rendered?(f.toggleClass(J,c),b.attr(f[0],"aria-disabled",c)):z.disabled=!!c;return e},enable:function(){return e.disable(h)},destroy:function(){var c=d[0],g=b.attr(c,N),u=d.data("qtip");e.rendered&&(f.stop(1,0).remove(),b.each(e.plugins,function(){this.destroy&&this.destroy()}));clearTimeout(e.timers.show);clearTimeout(e.timers.hide);j();if(!u||e===u)b.removeData(c,"qtip"),a.suppress&&g&&(b.attr(c,"title",g),d.removeAttr(N)),
d.removeAttr("aria-describedby");d.unbind(".qtip-"+s);delete V[e.id];return d}})}function $(d){function a(a,b,e){if(q.tip){var a=i.corner.clone(),b=e.adjusted,m=d.options.position.adjust.method.split(" "),f=m[0],m=m[1]||m[0],g=h,k=h,s=0,c=0,j,n={},v;i.corner.fixed!==p&&("shift"===f&&"x"===a.precedance&&b.left&&"center"!==a.y?a.precedance="x"===a.precedance?"y":"x":"flip"===f&&b.left&&(a.x="center"===a.x?0<b.left?"left":"right":"left"===a.x?"right":"left"),"shift"===m&&"y"===a.precedance&&b.top&&"center"!==
a.x?a.precedance="y"===a.precedance?"x":"y":"flip"===m&&b.top&&(a.y="center"===a.y?0<b.top?"top":"bottom":"top"===a.y?"bottom":"top"),a.string()!==y.corner.string()&&(y.top!==b.top||y.left!==b.left)&&i.update(a,h));j=i.position(a,b);j.right!==K&&(j.left=-j.right);j.bottom!==K&&(j.top=-j.bottom);j.user=Math.max(0,r.offset);if(g="shift"===f&&!!b.left)if("center"===a.x)n["margin-left"]=s=j["margin-left"]-b.left;else{v=j.right!==K?[b.left,-j.left]:[-b.left,j.left];if((s=Math.max(v[0],v[1]))>v[0])e.left-=
b.left,g=h;n[j.right!==K?"right":"left"]=s}if(k="shift"===m&&!!b.top)if("center"===a.y)n["margin-top"]=c=j["margin-top"]-b.top;else{v=j.bottom!==K?[b.top,-j.top]:[-b.top,j.top];if((c=Math.max(v[0],v[1]))>v[0])e.top-=b.top,k=h;n[j.bottom!==K?"bottom":"top"]=c}q.tip.css(n).toggle(!(s&&c||"center"===a.x&&c||"center"===a.y&&s));e.left-=j.left.charAt?j.user:"shift"!==f||k||!g&&!k?j.left:0;e.top-=j.top.charAt?j.user:"shift"!==m||g||!g&&!k?j.top:0;y.left=b.left;y.top=b.top;y.corner=a.clone()}}function s(a,
b,d){var b=!b?a[a.precedance]:b,e=t.hasClass(O),a=q.titlebar&&"top"===a.y?q.titlebar:q.content,b="border-"+b+"-width";t.addClass(O);a=parseInt(a.css(b),10);a=(d?a||parseInt(t.css(b),10):a)||0;t.toggleClass(O,e);return a}function v(a){var b="y"===a.precedance,d=B[b?"width":"height"],e=B[b?"height":"width"],f=-1<a.string().indexOf("center"),g=d*(f?0.5:1),i=Math.pow,a=Math.round,h=Math.sqrt(i(g,2)+i(e,2)),g=[j/g*h,j/e*h];g[2]=Math.sqrt(i(g[0],2)-i(j,2));g[3]=Math.sqrt(i(g[1],2)-i(j,2));f=(h+g[2]+g[3]+
(f?0:g[0]))/h;d=[a(f*e),a(f*d)];return{height:d[b?0:1],width:d[b?1:0]}}var i=this,r=d.options.style.tip,q=d.elements,t=q.tooltip,y={top:0,left:0},B={width:r.width,height:r.height},n,H,j=r.border||0,e=!!(b("<canvas />")[0]||{}).getContext;i.corner=C;i.mimic=C;i.border=j;i.offset=r.offset;i.size=B;d.checks.tip={"^position.my|style.tip.(corner|mimic|border)$":function(){i.init()||i.destroy();d.reposition()},"^style.tip.(height|width)$":function(){B={width:r.width,height:r.height};i.create();i.update();
d.reposition()},"^content.title.text|style.(classes|widget)$":function(){q.tip&&i.update()}};b.extend(i,{init:function(){var d=i.detectCorner()&&(e||b.browser.msie);d&&(i.create(),i.update(),t.unbind(".qtip-tip").bind("tooltipmove.qtip-tip",a));return d},detectCorner:function(){var a=r.corner,b=d.options.position,e=b.at,b=b.my.string?b.my.string():b.my;if(a===h||b===h&&e===h)return h;a===p?i.corner=new D.Corner(b):a.string||(i.corner=new D.Corner(a),i.corner.fixed=p);y.corner=new D.Corner(i.corner.string());
return"centercenter"!==i.corner.string()},detectColours:function(a){var e,j,h=q.tip.css("cssText","");e=a||i.corner;var f=e[e.precedance],a="border-"+f+"-color";j="border"+f.charAt(0)+f.substr(1)+"Color";var f=/rgba?\(0, 0, 0(, 0)?\)|transparent|#123456/i,g=b(document.body).css("color");d.elements.content.css("color");var k=q.titlebar&&("top"===e.y||"center"===e.y&&h.position().top+B.height/2+r.offset<q.titlebar.outerHeight(1))?q.titlebar:q.content;t.addClass(O);n=e=h.css("background-color");H=j=
h[0].style[j]||h.css(a)||t.css(a);if(!e||f.test(e))n=k.css("background-color")||"transparent",f.test(n)&&(n=t.css("background-color")||e);if(!j||f.test(j)||j===g)H=k.css(a)||"transparent",f.test(H)&&(H=j);b("*",h).add(h).css("cssText","background-color:transparent !important;border:0 !important;");t.removeClass(O)},create:function(){var a=B.width,d=B.height;q.tip&&q.tip.remove();q.tip=b("<div />",{"class":"ui-tooltip-tip"}).css({width:a,height:d}).prependTo(t);e?b("<canvas />").appendTo(q.tip)[0].getContext("2d").save():
(q.tip.html('<vml:shape coordorigin="0,0" style="display:inline-block; position:absolute; behavior:url(#default#VML);"></vml:shape><vml:shape coordorigin="0,0" style="display:inline-block; position:absolute; behavior:url(#default#VML);"></vml:shape>'),b("*",q.tip).bind("click mousedown",function(a){a.stopPropagation()}))},update:function(a,d){var t=q.tip,m=t.children(),f=B.width,g=B.height,k=r.mimic,z=Math.round,c,G,x;a||(a=y.corner||i.corner);k===h?k=a:(k=new D.Corner(k),k.precedance=a.precedance,
"inherit"===k.x?k.x=a.x:"inherit"===k.y?k.y=a.y:k.x===k.y&&(k[a.precedance]=a[a.precedance]));c=k.precedance;i.detectColours(a);"transparent"!==H&&"#123456"!==H?(j=s(a,C,p),0===r.border&&0<j&&(n=H),i.border=j=r.border!==p?r.border:j):i.border=j=0;x=k;var A=Math.ceil(f/2),J=Math.ceil(g/2),A={bottomright:[[0,0],[f,g],[f,0]],bottomleft:[[0,0],[f,0],[0,g]],topright:[[0,g],[f,0],[f,g]],topleft:[[0,0],[0,g],[f,g]],topcenter:[[0,g],[A,0],[f,g]],bottomcenter:[[0,0],[f,0],[A,g]],rightcenter:[[0,0],[f,J],[0,
g]],leftcenter:[[f,0],[f,g],[0,J]]};A.lefttop=A.bottomright;A.righttop=A.bottomleft;A.leftbottom=A.topright;A.rightbottom=A.topleft;G=A[x.string()];i.size=x=v(a);t.css(x);t="y"===a.precedance?[z("left"===k.x?j:"right"===k.x?x.width-f-j:(x.width-f)/2),z("top"===k.y?x.height-g:0)]:[z("left"===k.x?x.width-f:0),z("top"===k.y?j:"bottom"===k.y?x.height-g-j:(x.height-g)/2)];e?(m.attr(x),m=m[0].getContext("2d"),m.restore(),m.save(),m.clearRect(0,0,3E3,3E3),m.translate(t[0],t[1]),m.beginPath(),m.moveTo(G[0][0],
G[0][1]),m.lineTo(G[1][0],G[1][1]),m.lineTo(G[2][0],G[2][1]),m.closePath(),m.fillStyle=n,m.strokeStyle=H,m.lineWidth=2*j,m.lineJoin="miter",m.miterLimit=100,j&&m.stroke(),m.fill()):(G="m"+G[0][0]+","+G[0][1]+" l"+G[1][0]+","+G[1][1]+" "+G[2][0]+","+G[2][1]+" xe",t[2]=j&&/^(r|b)/i.test(a.string())?8===parseFloat(b.browser.version,10)?2:1:0,m.css({antialias:""+(-1<k.string().indexOf("center")),left:t[0]-t[2]*Number("x"===c),top:t[1]-t[2]*Number("y"===c),width:f+j,height:g+j}).each(function(a){var c=
b(this);c[c.prop?"prop":"attr"]({coordsize:f+j+" "+(g+j),path:G,fillcolor:n,filled:!!a,stroked:!a}).css({display:j||a?"block":"none"});!a&&""===c.html()&&c.html('<vml:stroke weight="'+2*j+'px" color="'+H+'" miterlimit="1000" joinstyle="miter"  style="behavior:url(#default#VML); display:inline-block;" />')}));d!==h&&i.position(a)},position:function(a){var d=q.tip,e={},m=Math.max(0,r.offset),f,g,k;if(r.corner===h||!d)return h;a=a||i.corner;f=a.precedance;g=v(a);k=[a.x,a.y];"x"===f&&k.reverse();b.each(k,
function(d,c){var i,h;if("center"===c)i="y"===f?"left":"top",e[i]="50%",e["margin-"+i]=-Math.round(g["y"===f?"width":"height"]/2)+m;else{i=s(a,c,p);h=b.browser.mozilla;var k=a.y+(h?"":"-")+a.x;h=(h?"-moz-":b.browser.webkit?"-webkit-":"")+(h?"border-radius-"+k:"border-"+k+"-radius");h=parseInt((q.titlebar&&"top"===a.y?q.titlebar:q.content).css(h),10)||parseInt(t.css(h),10)||0;e[c]=d?j?s(a,c):0:m+(h>i?h:0)}});e[a[f]]-=g["x"===f?"width":"height"];d.css({top:"",bottom:"",left:"",right:"",margin:""}).css(e);
return e},destroy:function(){q.tip&&q.tip.remove();t.unbind(".qtip-tip")}});i.init()}var p=!0,h=!1,C=null,K,B,D,L,V={},A="ui-tooltip",U="ui-widget",J="ui-state-disabled",Q="div.qtip."+A,W=A+"-default",T=A+"-focus",Z=A+"-hover",O=A+"-fluid",N="oldtitle",S;B=b.fn.qtip=function(d,a,s){var v=(""+d).toLowerCase(),i=C,r=b.makeArray(arguments).slice(1),q=r[r.length-1],t=this[0]?b.data(this[0],"qtip"):C;if(!arguments.length&&t||"api"===v)return t;if("string"===typeof d)return this.each(function(){var d=b.data(this,
"qtip");if(!d)return p;q&&q.timeStamp&&(d.cache.event=q);if(("option"===v||"options"===v)&&a)if(b.isPlainObject(a)||s!==K)d.set(a,s);else return i=d.get(a),h;else d[v]&&d[v].apply(d[v],r)}),i!==C?i:this;if("object"===typeof d||!arguments.length)return t=R(b.extend(p,{},d)),B.bind.call(this,t,q)};B.bind=function(d,a){return this.each(function(s){function v(a){function d(){y.render("object"===typeof a||i.show.ready);r.show.add(r.hide).unbind(t)}if(y.cache.disabled)return h;y.cache.event=b.extend({},
a);y.cache.target=a?b(a.target):[K];0<i.show.delay?(clearTimeout(y.timers.show),y.timers.show=setTimeout(d,i.show.delay),q.show!==q.hide&&r.hide.bind(q.hide,function(){clearTimeout(y.timers.show)})):d()}var i,r,q,t,y,s=b.isArray(d.id)?d.id[s]:d.id,s=!s||s===h||1>s.length||V[s]?B.nextid++:V[s]=s;t=".qtip-"+s+"-create";a:{var A,n,H,j,e,u=b(this),w=b(document.body),I=this===document?w:u;n=u.metadata?u.metadata(d.metadata):C;j="html5"===d.metadata.type&&n?n[d.metadata.name]:C;var m=u.data(d.metadata.name||
"qtipopts");try{m="string"===typeof m?(new Function("return "+m))():m}catch(f){P("Unable to parse HTML5 attribute data: "+m)}j=b.extend(p,{},B.defaults,d,"object"===typeof m?R(m):C,R(j||n));n=j.position;j.id=s;if("boolean"===typeof j.content.text)if(H=u.attr(j.content.attr),j.content.attr!==h&&H)j.content.text=H;else{P("Unable to locate content for tooltip! Aborting render of tooltip on element: ",u);y=h;break a}n.container.length||(n.container=w);n.target===h&&(n.target=I);j.show.target===h&&(j.show.target=
I);j.show.solo===p&&(j.show.solo=n.container.closest("body"));j.hide.target===h&&(j.hide.target=I);j.position.viewport===p&&(j.position.viewport=n.container);n.container=n.container.eq(0);n.at=new D.Corner(n.at);n.my=new D.Corner(n.my);if(b.data(this,"qtip"))if(j.overwrite)u.qtip("destroy");else if(j.overwrite===h){y=h;break a}j.suppress&&(e=b.attr(this,"title"))&&b(this).removeAttr("title").attr(N,e);A=new X(u,j,s,!!H);b.data(this,"qtip",A);u.bind("remove.qtip-"+s+" removeqtip.qtip-"+s,function(){A.destroy()});
y=A}if(y===h)return p;i=y.options;b.each(D,function(){"initialize"===this.initialize&&this(y)});r={show:i.show.target,hide:i.hide.target};q={show:b.trim(""+i.show.event).replace(/ /g,t+" ")+t,hide:b.trim(""+i.hide.event).replace(/ /g,t+" ")+t};/mouse(over|enter)/i.test(q.show)&&!/mouse(out|leave)/i.test(q.hide)&&(q.hide+=" mouseleave"+t);r.show.bind("mousemove"+t,function(a){L={pageX:a.pageX,pageY:a.pageY,type:"mousemove"};y.cache.onTarget=p});r.show.bind(q.show,v);(i.show.ready||i.prerender)&&v(a)})};
D=B.plugins={Corner:function(b){b=(""+b).replace(/([A-Z])/," $1").replace(/middle/gi,"center").toLowerCase();this.x=(b.match(/left|right/i)||b.match(/center/)||["inherit"])[0].toLowerCase();this.y=(b.match(/top|bottom|center/i)||["inherit"])[0].toLowerCase();b=b.charAt(0);this.precedance="t"===b||"b"===b?"y":"x";this.string=function(){return"y"===this.precedance?this.y+this.x:this.x+this.y};this.abbrev=function(){var a=this.x.substr(0,1),b=this.y.substr(0,1);return a===b?a:"c"===a||"c"!==a&&"c"!==
b?b+a:a+b};this.clone=function(){return{x:this.x,y:this.y,precedance:this.precedance,string:this.string,abbrev:this.abbrev,clone:this.clone}}},offset:function(d,a){var h=d.offset(),v=d.closest("body")[0],i=a,r,q,p;if(i){do if("static"!==i.css("position")&&(q=i.position(),h.left-=q.left+(parseInt(i.css("borderLeftWidth"),10)||0)+(parseInt(i.css("marginLeft"),10)||0),h.top-=q.top+(parseInt(i.css("borderTopWidth"),10)||0)+(parseInt(i.css("marginTop"),10)||0),!r&&"hidden"!==(p=i.css("overflow"))&&"visible"!==
p))r=i;while((i=b(i[0].offsetParent)).length);r&&r[0]!==v&&(v=r,h.left+=1*v.scrollLeft(),h.top+=1*v.scrollTop())}return h},iOS:parseFloat((""+(/CPU.*OS ([0-9_]{1,3})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||[0,""])[1]).replace("undefined","3_2").replace("_","."))||h,fn:{attr:function(d,a){if(this.length){var h=this[0],p=b.data(h,"qtip");if("title"===d&&p&&"object"===typeof p&&p.options.suppress){if(2>arguments.length)return b.attr(h,N);p&&("title"===p.options.content.attr&&p.cache.attr)&&
p.set("content.text",a);return this.attr(N,a)}}return b.fn.attr_replacedByqTip.apply(this,arguments)},clone:function(d){b([]);var a=b.fn.clone_replacedByqTip.apply(this,arguments);d||a.filter("["+N+"]").attr("title",function(){return b.attr(this,N)}).removeAttr(N);return a}}};b.each(D.fn,function(d,a){if(!a||b.fn[d+"_replacedByqTip"])return p;var h=b.fn[d+"_replacedByqTip"]=b.fn[d];b.fn[d]=function(){return a.apply(this,arguments)||h.apply(this,arguments)}});b.ui||(b.cleanData_replacedByqTip=b.cleanData,
b.cleanData=function(d){for(var a=0,h;(h=d[a])!==K;a++)try{b(h).triggerHandler("removeqtip")}catch(p){}b.cleanData_replacedByqTip(d)});B.version="2.0.0pre";B.nextid=0;B.inactiveEvents="click dblclick mousedown mouseup mousemove mouseleave mouseenter".split(" ");B.zindex=15E3;B.defaults={prerender:h,id:h,overwrite:p,suppress:p,content:{text:p,attr:"title",title:{text:h,button:h}},position:{my:"top left",at:"bottom right",target:h,container:h,viewport:h,adjust:{x:0,y:0,mouse:p,resize:p,method:"flip flip"},
effect:function(d,a){b(this).animate(a,{duration:200,queue:h})}},show:{target:h,event:"mouseenter",effect:p,delay:90,solo:h,ready:h,autofocus:h},hide:{target:h,event:"mouseleave",effect:p,delay:0,fixed:h,inactive:h,leave:"window",distance:h},style:{classes:"",widget:h,width:h,height:h,def:p},events:{render:C,move:C,show:C,hide:C,toggle:C,visible:C,hidden:C,focus:C,blur:C}};D.tip=function(b){var a=b.plugins.tip;return"object"===typeof a?a:b.plugins.tip=new $(b)};D.tip.initialize="render";D.tip.sanitize=
function(b){var a=b.style;a&&"tip"in a&&(a=b.style.tip,"object"!==typeof a&&(b.style.tip={corner:a}),/string|boolean/i.test(typeof a.corner)||(a.corner=p),"number"!==typeof a.width&&delete a.width,"number"!==typeof a.height&&delete a.height,"number"!==typeof a.border&&a.border!==p&&delete a.border,"number"!==typeof a.offset&&delete a.offset)};b.extend(p,B.defaults,{style:{tip:{corner:p,mimic:h,width:6,height:6,border:p,offset:0}}})});
