/*!
* jquery.qtip. The jQuery tooltip plugin
*
* Copyright (c) 2009 Craig Thompson
* http://craigsworks.com
*
* Licensed under MIT
* http://www.opensource.org/licenses/mit-license.php
*
* Launch  : February 2009
* Version : 1.0.0-rc3
* Released: Tuesday 12th May, 2009 - 00:00
* Debug: jquery.qtip.debug.js
* A few minor fixes added by Dustin Moore, dustmoo@gmail.com---
* ---Added Craigs opacity fix for to the afterShow function to prevent the tip opacity rendering
* ---Raised the z-index to a higher maximum to prevent z-index conflicts
* ---Added functionality so that unfocus can be used with other hide actions, i.e. unfocus and mouseout
* ---Various IE fixes as well as jQuery 1.4.1 compatability updates.
*/

(function(c){function C(b,e,d){var a=this;a.id=d;a.options=e;a.status={animated:!1,rendered:!1,disabled:!1,focused:!1};a.elements={target:b.addClass(a.options.style.classes.target),tooltip:null,wrapper:null,content:null,contentWrapper:null,title:null,button:null,tip:null,bgiframe:null};a.cache={mouse:{},position:{},toggle:0};a.timers={};c.extend(a,a.options.api,{show:function(b){function e(){c(this).css({opacity:""});"static"!==a.options.position.type&&a.focus();a.onShow.call(a,b);c.browser.msie&&
a.elements.tooltip.get(0).style.removeAttribute("filter")}var d;if(!a.status.rendered)return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"show");if("none"!==a.elements.tooltip.css("display"))return a;a.elements.tooltip.stop(!0,!1);if(!1===a.beforeShow.call(a,b))return a;a.cache.toggle=1;"static"!==a.options.position.type&&a.updatePosition(b,0<a.options.show.effect.length);"object"==typeof a.options.show.solo?d=c(a.options.show.solo):!0===a.options.show.solo&&(d=c("div.qtip").not(a.elements.tooltip));
d&&d.each(function(){!0===c(this).qtip("api").status.rendered&&c(this).qtip("api").hide()});if("function"==typeof a.options.show.effect.type)a.options.show.effect.type.call(a.elements.tooltip,a.options.show.effect.length),a.elements.tooltip.queue(function(){e();c(this).dequeue()});else{switch(a.options.show.effect.type.toLowerCase()){case "fade":a.elements.tooltip.fadeIn(a.options.show.effect.length,e);break;case "slide":a.elements.tooltip.slideDown(a.options.show.effect.length,function(){e();"static"!==
a.options.position.type&&a.updatePosition(b,!0)});break;case "grow":a.elements.tooltip.show(a.options.show.effect.length,e);break;default:a.elements.tooltip.show(null,e),a.elements.tooltip.css({opacity:""})}a.elements.tooltip.addClass(a.options.style.classes.active)}return c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_SHOWN,"show")},hide:function(b){function e(){a.onHide.call(a,b)}if(a.status.rendered){if("none"===a.elements.tooltip.css("display"))return a}else return c.fn.qtip.log.error.call(a,
2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"hide");clearTimeout(a.timers.show);a.elements.tooltip.stop(!0,!1);if(!1===a.beforeHide.call(a,b))return a;a.cache.toggle=0;if("function"==typeof a.options.hide.effect.type)a.options.hide.effect.type.call(a.elements.tooltip,a.options.hide.effect.length),a.elements.tooltip.queue(function(){e();c(this).dequeue()});else{switch(a.options.hide.effect.type.toLowerCase()){case "fade":a.elements.tooltip.fadeOut(a.options.hide.effect.length,e);break;case "slide":a.elements.tooltip.slideUp(a.options.hide.effect.length,
e);break;case "grow":a.elements.tooltip.hide(a.options.hide.effect.length,e);break;default:a.elements.tooltip.hide(null,e)}a.elements.tooltip.removeClass(a.options.style.classes.active)}return c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_HIDDEN,"hide")},updatePosition:function(b,e){var d,f,j,h,m,k,g;if(a.status.rendered){if("static"==a.options.position.type)return c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.CANNOT_POSITION_STATIC,"updatePosition")}else return c.fn.qtip.log.error.call(a,
2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"updatePosition");f={position:{left:0,top:0},dimensions:{height:0,width:0},corner:a.options.position.corner.target};j={position:a.getPosition(),dimensions:a.getDimensions(),corner:a.options.position.corner.tooltip};if("mouse"!==a.options.position.target){if("area"==a.options.position.target.get(0).nodeName.toLowerCase()){h=a.options.position.target.attr("coords").split(",");for(d=0;d<h.length;d++)h[d]=parseInt(h[d]);d=a.options.position.target.parent("map").attr("name");
m=c('img[usemap="#'+d+'"]:first').offset();f.position={left:Math.floor(m.left+h[0]),top:Math.floor(m.top+h[1])};switch(a.options.position.target.attr("shape").toLowerCase()){case "rect":f.dimensions={width:Math.ceil(Math.abs(h[2]-h[0])),height:Math.ceil(Math.abs(h[3]-h[1]))};break;case "circle":f.dimensions={width:h[2]+1,height:h[2]+1};break;case "poly":f.dimensions={width:h[0],height:h[1]};for(d=0;d<h.length;d++)0==d%2?(h[d]>f.dimensions.width&&(f.dimensions.width=h[d]),h[d]<h[0]&&(f.position.left=
Math.floor(m.left+h[d]))):(h[d]>f.dimensions.height&&(f.dimensions.height=h[d]),h[d]<h[1]&&(f.position.top=Math.floor(m.top+h[d])));f.dimensions.width-=f.position.left-m.left;f.dimensions.height-=f.position.top-m.top;break;default:return c.fn.qtip.log.error.call(a,4,c.fn.qtip.constants.INVALID_AREA_SHAPE,"updatePosition")}f.dimensions.width-=2;f.dimensions.height-=2}else 1===a.options.position.target.add(document.body).length?(f.position={left:c(document).scrollLeft(),top:c(document).scrollTop()},
f.dimensions={height:c(window).height(),width:c(window).width()}):(f.position="undefined"!==typeof a.options.position.target.attr("qtip")?a.options.position.target.qtip("api").cache.position:a.options.position.target.offset(),f.dimensions={height:a.options.position.target.outerHeight(),width:a.options.position.target.outerWidth()});k=c.extend({},f.position);/right/i.test(f.corner)&&(k.left+=f.dimensions.width);/bottom/i.test(f.corner)&&(k.top+=f.dimensions.height);/((top|bottom)Middle)|center/.test(f.corner)&&
(k.left+=f.dimensions.width/2);/((left|right)Middle)|center/.test(f.corner)&&(k.top+=f.dimensions.height/2)}else f.position=k={left:a.cache.mouse.x,top:a.cache.mouse.y},f.dimensions={height:1,width:1};/right/i.test(j.corner)&&(k.left-=j.dimensions.width);/bottom/i.test(j.corner)&&(k.top-=j.dimensions.height);/((top|bottom)Middle)|center/.test(j.corner)&&(k.left-=j.dimensions.width/2);/((left|right)Middle)|center/.test(j.corner)&&(k.top-=j.dimensions.height/2);h=c.browser.msie?1:0;c.browser.msie&&
parseInt(c.browser.version.charAt(0));0<a.options.style.border.radius&&(/Left/i.test(j.corner)?k.left-=a.options.style.border.radius:/Right/i.test(j.corner)&&(k.left+=a.options.style.border.radius),/Top/i.test(j.corner)?k.top-=a.options.style.border.radius:/Bottom/i.test(j.corner)&&(k.top+=a.options.style.border.radius));h&&(/top/i.test(j.corner)?k.top-=h:/bottom/i.test(j.corner)&&(k.top+=h),/left/i.test(j.corner)?k.left-=h:/right/i.test(j.corner)&&(k.left+=h),/leftMiddle|rightMiddle/.test(j.corner)&&
(k.top-=1));!0===a.options.position.adjust.screen&&(k=D.call(a,k,f,j));"mouse"===a.options.position.target&&!0===a.options.position.adjust.mouse&&(f=!0===a.options.position.adjust.screen&&a.elements.tip?a.elements.tip.attr("rel"):a.options.position.corner.tooltip,k.left+=/right/i.test(f)?-6:6,k.top+=/bottom/i.test(f)?-6:6);!a.elements.bgiframe&&(c.browser.msie&&6==parseInt(c.browser.version.charAt(0)))&&c("select, object").each(function(){g=c(this).offset();g.bottom=g.top+c(this).height();g.right=
g.left+c(this).width();k.top+j.dimensions.height>=g.top&&k.left+j.dimensions.width>=g.left&&E.call(a)});k.left+=a.options.position.adjust.x;k.top+=a.options.position.adjust.y;f=a.getPosition();if(k.left!=f.left||k.top!=f.top){f=a.beforePositionUpdate.call(a,b);if(!1===f)return a;a.cache.position=k;!0===e?(a.status.animated=!0,a.elements.tooltip.animate(k,200,"swing",function(){a.status.animated=!1})):a.elements.tooltip.css(k);a.onPositionUpdate.call(a,b);"undefined"!==typeof b&&(b.type&&"mousemove"!==
b.type)&&c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_POSITION_UPDATED,"updatePosition")}return a},updateWidth:function(b){if(a.status.rendered){if(void 0!=b&&"number"!==typeof b)return c.fn.qtip.log.error.call(a,2,"newWidth must be of type number","updateWidth")}else return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"updateWidth");var d=a.elements.contentWrapper.siblings().add(a.elements.tip).add(a.elements.button),e=a.elements.wrapper.add(a.elements.contentWrapper.children()),
f=a.options.style.width.max,j=a.options.style.width.min;b||("number"===typeof a.options.style.width.value?b=a.options.style.width.value:(a.elements.tooltip.css({width:"auto"}),d.hide(),c.browser.msie&&e.css({zoom:""}),b=a.getDimensions().width,a.options.style.width.value||(b=Math.min(Math.max(b,j),f))));b%2&&(b-=1);a.elements.tooltip.width(b);d.show();a.options.style.border.radius&&a.elements.tooltip.find(".qtip-betweenCorners").each(function(){c(this).width(b-2*a.options.style.border.radius)});c.browser.msie&&
(e.css({zoom:1}),a.elements.bgiframe&&a.elements.bgiframe.width(b).height(a.getDimensions.height));return c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_WIDTH_UPDATED,"updateWidth")},updateStyle:function(b){var d,e,f,j;if(a.status.rendered){if("string"!==typeof b||!c.fn.qtip.styles[b])return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.STYLE_NOT_DEFINED,"updateStyle")}else return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"updateStyle");a.options.style=u.call(a,
c.fn.qtip.styles[b],a.options.user.style);a.elements.content.css(s(a.options.style));!1!==a.options.content.title.text&&a.elements.title.css(s(a.options.style.title,!0));a.elements.contentWrapper.css({borderColor:a.options.style.border.color});!1!==a.options.style.tip.corner&&(c("<canvas>").get(0).getContext?(b=a.elements.tooltip.find(".qtip-tip canvas:first"),e=b.get(0).getContext("2d"),e.clearRect(0,0,300,300),f=b.parent("div[rel]:first").attr("rel"),j=v(f,a.options.style.tip.size.width,a.options.style.tip.size.height),
w.call(a,b,j,a.options.style.tip.color||a.options.style.border.color)):c.browser.msie&&(b=a.elements.tooltip.find('.qtip-tip [nodeName="shape"]'),b.attr("fillcolor",a.options.style.tip.color||a.options.style.border.color)));0<a.options.style.border.radius&&(a.elements.tooltip.find(".qtip-betweenCorners").css({backgroundColor:a.options.style.border.color}),c("<canvas>").get(0).getContext?(d=x(a.options.style.border.radius),a.elements.tooltip.find(".qtip-wrapper canvas").each(function(){e=c(this).get(0).getContext("2d");
e.clearRect(0,0,300,300);f=c(this).parent("div[rel]:first").attr("rel");y.call(a,c(this),d[f],a.options.style.border.radius,a.options.style.border.color)})):c.browser.msie&&a.elements.tooltip.find('.qtip-wrapper [nodeName="arc"]').each(function(){c(this).attr("fillcolor",a.options.style.border.color)}));return c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_STYLE_UPDATED,"updateStyle")},updateContent:function(b,d){function e(){a.updateWidth();!1!==d&&("static"!==a.options.position.type&&a.updatePosition(a.elements.tooltip.is(":visible"),
!0),!1!==a.options.style.tip.corner&&q.call(a))}var f,j,h;if(a.status.rendered){if(!b)return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.NO_CONTENT_PROVIDED,"updateContent")}else return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"updateContent");f=a.beforeContentUpdate.call(a,b);if("string"==typeof f)b=f;else if(!1===f)return;c.browser.msie&&a.elements.contentWrapper.children().css({zoom:"normal"});b.jquery&&0<b.length?b.clone(!0).appendTo(a.elements.content).show():
a.elements.content.html(b);h=0;j=a.elements.content.find("img");j.length?c.fn.qtip.preload?(j.each(function(){preloaded=c('body > img[src="'+c(this).attr("src")+'"]:first');0<preloaded.length&&c(this).attr("width",preloaded.innerWidth()).attr("height",preloaded.innerHeight())}),e()):j.bind("load error",function(){++h===j.length&&e()}):e();a.updateWidth();!1!==d&&("static"!==a.options.position.type&&a.updatePosition(a.elements.tooltip.is(":visible"),!0),!1!==a.options.style.tip.corner&&q.call(a));
a.onContentUpdate.call(a);return c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_CONTENT_UPDATED,"loadContent")},loadContent:function(b,d,e){function f(b){a.onContentLoad.call(a);c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_CONTENT_LOADED,"loadContent");a.updateContent(b)}if(!a.status.rendered)return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"loadContent");if(!1===a.beforeContentLoad.call(a))return a;"post"==e?c.post(b,d,f):c.get(b,d,f);return a},updateTitle:function(b){if(a.status.rendered){if(!b)return c.fn.qtip.log.error.call(a,
2,c.fn.qtip.constants.NO_CONTENT_PROVIDED,"updateTitle")}else return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"updateTitle");returned=a.beforeTitleUpdate.call(a);if(!1===returned)return a;a.elements.button&&(a.elements.button=a.elements.button.clone(!0));a.elements.title.html(b);a.elements.button&&a.elements.title.prepend(a.elements.button);a.onTitleUpdate.call(a);return c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_TITLE_UPDATED,"updateTitle")},focus:function(b){var d,
e,f;if(a.status.rendered){if("static"==a.options.position.type)return c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.CANNOT_FOCUS_STATIC,"focus")}else return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"focus");d=parseInt(a.elements.tooltip.css("z-index"));e=32001+c("div.qtip[qtip]").length-1;if(!a.status.focused&&d!==e){d=a.beforeFocus.call(a,b);if(!1===d)return a;c("div.qtip[qtip]").not(a.elements.tooltip).each(function(){!0===c(this).qtip("api").status.rendered&&(f=
parseInt(c(this).css("z-index")),"number"==typeof f&&-1<f&&c(this).css({zIndex:parseInt(c(this).css("z-index"))-1}),c(this).qtip("api").status.focused=!1)});a.elements.tooltip.css({zIndex:e});a.status.focused=!0;a.onFocus.call(a,b);c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_FOCUSED,"focus")}return a},disable:function(b){if(!a.status.rendered)return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"disable");b?a.status.disabled?c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.TOOLTIP_ALREADY_DISABLED,
"disable"):(a.status.disabled=!0,c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_DISABLED,"disable")):a.status.disabled?(a.status.disabled=!1,c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_ENABLED,"disable")):c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.TOOLTIP_ALREADY_ENABLED,"disable");return a},destroy:function(){var b,d;if(!1===a.beforeDestroy.call(a))return a;a.status.rendered?(a.options.show.when.target.unbind("mousemove.qtip",a.updatePosition),a.options.show.when.target.unbind("mouseout.qtip",
a.hide),a.options.show.when.target.unbind(a.options.show.when.event+".qtip"),a.options.hide.when.target.unbind(a.options.hide.when.event+".qtip"),a.elements.tooltip.unbind(a.options.hide.when.event+".qtip"),a.elements.tooltip.unbind("mouseover.qtip",a.focus),a.elements.tooltip.remove()):a.options.show.when.target.unbind(a.options.show.when.event+".qtip-create");if("object"==typeof a.elements.target.data("qtip")&&(d=a.elements.target.data("qtip").interfaces,"object"==typeof d&&0<d.length))for(b=0;b<
d.length-1;b++)d[b].id==a.id&&d.splice(b,1);c.fn.qtip.interfaces.splice(a.id,1);"object"==typeof d&&0<d.length?a.elements.target.data("qtip").current=d.length-1:a.elements.target.removeData("qtip");a.onDestroy.call(a);c.fn.qtip.log.error.call(a,1,c.fn.qtip.constants.EVENT_DESTROYED,"destroy");return a.elements.target},getPosition:function(){var b,d;if(!a.status.rendered)return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"getPosition");(b="none"!==a.elements.tooltip.css("display")?
!1:!0)&&a.elements.tooltip.css({visiblity:"hidden"}).show();d=a.elements.tooltip.offset();b&&a.elements.tooltip.css({visiblity:"visible"}).hide();return d},getDimensions:function(){var b,d;if(!a.status.rendered)return c.fn.qtip.log.error.call(a,2,c.fn.qtip.constants.TOOLTIP_NOT_RENDERED,"getDimensions");(b=!a.elements.tooltip.is(":visible")?!0:!1)&&a.elements.tooltip.css({visiblity:"hidden"}).show();d={height:a.elements.tooltip.outerHeight(),width:a.elements.tooltip.outerWidth()};b&&a.elements.tooltip.css({visiblity:"visible"}).hide();
return d}})}function z(){var b,e,d;this.beforeRender.call(this);this.status.rendered=!0;this.elements.tooltip='<div qtip="'+this.id+'" class="qtip '+(this.options.style.classes.tooltip||this.options.style)+'"style="display:none; -moz-border-radius:0; -webkit-border-radius:0; border-radius:0;position:'+this.options.position.type+';">  <div class="qtip-wrapper" style="position:relative; overflow:hidden; text-align:left;">    <div class="qtip-contentWrapper" style="overflow:hidden;">       <div class="qtip-content '+
this.options.style.classes.content+'"></div></div></div></div>';this.elements.tooltip=c(this.elements.tooltip);this.elements.tooltip.appendTo(this.options.position.container);this.elements.tooltip.data("qtip",{current:0,interfaces:[this]});this.elements.wrapper=this.elements.tooltip.children("div:first");this.elements.contentWrapper=this.elements.wrapper.children("div:first").css({background:this.options.style.background});this.elements.content=this.elements.contentWrapper.children("div:first").css(s(this.options.style));
c.browser.msie&&this.elements.wrapper.add(this.elements.content).css({zoom:1});/unfocus/i.test(this.options.hide.when.event)&&this.elements.tooltip.attr("unfocus",!0);"number"==typeof this.options.style.width.value&&this.updateWidth();if(c("<canvas>").get(0).getContext||c.browser.msie){if(0<this.options.style.border.radius){var a,l,n,p,f,j;a=this;a.elements.wrapper.find(".qtip-borderBottom, .qtip-borderTop").remove();b=a.options.style.border.width;l=a.options.style.border.radius;n=a.options.style.border.color||
a.options.style.tip.color;p=x(l);e={};for(d in p)e[d]='<div rel="'+d+'" style="'+(/Left/.test(d)?"left":"right")+":0; position:absolute; height:"+l+"px; width:"+l+'px; overflow:hidden; line-height:0.1px; font-size:1px">',c("<canvas>").get(0).getContext?e[d]+='<canvas height="'+l+'" width="'+l+'" style="vertical-align: top"></canvas>':c.browser.msie&&(f=2*l+3,e[d]+='<v:arc stroked="false" fillcolor="'+n+'" startangle="'+p[d][0]+'" endangle="'+p[d][1]+'" style="width:'+f+"px; height:"+f+"px; margin-top:"+
(/bottom/.test(d)?-2:-1)+"px; margin-left:"+(/Right/.test(d)?p[d][2]-3.5:-1)+'px; vertical-align:top; display:inline-block; behavior:url(#default#VML)"></v:arc>'),e[d]+="</div>";d=a.getDimensions().width-2*Math.max(b,l);d='<div class="qtip-betweenCorners" style="height:'+l+"px; width:"+d+"px; overflow:hidden; background-color:"+n+'; line-height:0.1px; font-size:1px;">';a.elements.wrapper.prepend('<div class="qtip-borderTop" dir="ltr" style="height:'+l+"px; margin-left:"+l+'px; line-height:0.1px; font-size:1px; padding:0;">'+
e.topLeft+e.topRight+d);a.elements.wrapper.append('<div class="qtip-borderBottom" dir="ltr" style="height:'+l+"px; margin-left:"+l+'px; line-height:0.1px; font-size:1px; padding:0;">'+e.bottomLeft+e.bottomRight+d);c("<canvas>").get(0).getContext?a.elements.wrapper.find("canvas").each(function(){j=p[c(this).parent("[rel]:first").attr("rel")];y.call(a,c(this),j,l,n)}):c.browser.msie&&a.elements.tooltip.append('<v:image style="behavior:url(#default#VML);"></v:image>');e=Math.max(l,l+(b-l));b=Math.max(b-
l,0);a.elements.contentWrapper.css({border:"0px solid "+n,borderWidth:b+"px "+e+"px"})}else this.elements.contentWrapper.css({border:this.options.style.border.width+"px solid "+this.options.style.border.color});!1!==this.options.style.tip.corner&&A.call(this)}else this.elements.contentWrapper.css({border:this.options.style.border.width+"px solid "+this.options.style.border.color}),this.options.style.border.radius=0,this.options.style.tip.corner=!1,c.fn.qtip.log.error.call(this,2,c.fn.qtip.constants.CANVAS_VML_NOT_SUPPORTED,
"render");"string"==typeof this.options.content.text&&0<this.options.content.text.length||this.options.content.text.jquery&&0<this.options.content.text.length?b=this.options.content.text:"string"==typeof this.elements.target.attr("title")&&0<this.elements.target.attr("title").length?(b=this.elements.target.attr("title").replace("\\n","<br />"),this.elements.target.attr("title","")):"string"==typeof this.elements.target.attr("alt")&&0<this.elements.target.attr("alt").length?(b=this.elements.target.attr("alt").replace("\\n",
"<br />"),this.elements.target.attr("alt","")):(b=" ",c.fn.qtip.log.error.call(this,1,c.fn.qtip.constants.NO_VALID_CONTENT,"render"));if(!1!==this.options.content.title.text){var h=this;null!==h.elements.title&&h.elements.title.remove();h.elements.title=c('<div class="'+h.options.style.classes.title+'">').css(s(h.options.style.title,!0)).css({zoom:c.browser.msie?1:0}).prependTo(h.elements.contentWrapper);h.options.content.title.text&&h.updateTitle.call(h,h.options.content.title.text);!1!==h.options.content.title.button&&
"string"==typeof h.options.content.title.button&&(h.elements.button=c('<a class="'+h.options.style.classes.button+'" style="float:right; position: relative"></a>').css(s(h.options.style.button,!0)).html(h.options.content.title.button).prependTo(h.elements.title).click(function(a){h.status.disabled||h.hide(a)}))}this.updateContent(b);var m=function(a){!0!==g.status.disabled&&("inactive"==g.options.hide.when.event&&(c(q).each(function(){r.bind(this+".qtip-inactive",t);g.elements.content.bind(this+".qtip-inactive",
t)}),t()),clearTimeout(g.timers.show),clearTimeout(g.timers.hide),0<g.options.show.delay?g.timers.show=setTimeout(function(){g.show(a)},g.options.show.delay):g.show(a))},k=function(a){if(!0!==g.status.disabled){if(!0===g.options.hide.fixed&&/mouse(out|leave)/i.test(g.options.hide.when.event)&&0<c(a.relatedTarget).parents("div.qtip[qtip]").length)return a.stopPropagation(),a.preventDefault(),clearTimeout(g.timers.hide),!1;clearTimeout(g.timers.show);clearTimeout(g.timers.hide);g.elements.tooltip.stop(!0,
!0);g.timers.hide=setTimeout(function(){g.hide(a)},g.options.hide.delay)}},g,r,q;g=this;b=g.options.show.when.target;r=g.options.hide.when.target;g.options.hide.fixed&&(r=r.add(g.elements.tooltip));if("inactive"==g.options.hide.when.event){q="click dblclick mousedown mouseup mousemove mouseout mouseenter mouseleave mouseover touchstart".split(" ");var t=function(a){!0!==g.status.disabled&&(clearTimeout(g.timers.inactive),g.timers.inactive=setTimeout(function(){c(q).each(function(){r.unbind(this+".qtip-inactive");
g.elements.content.unbind(this+".qtip-inactive")});g.hide(a)},g.options.hide.delay))}}else!0===g.options.hide.fixed&&g.elements.tooltip.bind("mouseover.qtip",function(){!0!==g.status.disabled&&clearTimeout(g.timers.hide)});1===g.options.show.when.target.add(g.options.hide.when.target).length&&g.options.show.when.event==g.options.hide.when.event&&"inactive"!==g.options.hide.when.event||"unfocus"==g.options.hide.when.event?(g.cache.toggle=0,b.bind(g.options.show.when.event+".qtip",function(a){0==g.cache.toggle?
m(a):k(a)})):(b.bind(g.options.show.when.event+".qtip",m),"inactive"!==g.options.hide.when.event&&r.bind(g.options.hide.when.event+".qtip",k));/(fixed|absolute)/.test(g.options.position.type)&&g.elements.tooltip.bind("mouseover.qtip",g.focus);"mouse"===g.options.position.target&&"static"!==g.options.position.type&&b.bind("mousemove.qtip",function(a){g.cache.mouse={x:a.pageX,y:a.pageY};!1===g.status.disabled&&(!0===g.options.position.adjust.mouse&&"static"!==g.options.position.type&&"none"!==g.elements.tooltip.css("display"))&&
g.updatePosition(a)});!0===this.options.show.ready&&this.show();!1!==this.options.content.url&&(b=this.options.content.url,e=this.options.content.data,d=this.options.content.method||"get",this.loadContent(b,e,d));this.onRender.call(this);c.fn.qtip.log.error.call(this,1,c.fn.qtip.constants.EVENT_RENDERED,"render")}function y(b,c,d,a){b=b.get(0).getContext("2d");b.fillStyle=a;b.beginPath();b.arc(c[0],c[1],d,0,2*Math.PI,!1);b.fill()}function A(b){var e,d,a,l;null!==this.elements.tip&&this.elements.tip.remove();
e=this.options.style.tip.color||this.options.style.border.color;!1!==this.options.style.tip.corner&&(b||(b=this.options.style.tip.corner),d=v(b,this.options.style.tip.size.width,this.options.style.tip.size.height),this.elements.tip='<div class="'+this.options.style.classes.tip+'" dir="ltr" rel="'+b+'" style="position:absolute; height:'+this.options.style.tip.size.height+"px; width:"+this.options.style.tip.size.width+'px; margin:0 auto; line-height:0.1px; font-size:1px;"></div>',this.elements.tooltip.prepend(this.elements.tip),
c("<canvas>").get(0).getContext?a='<canvas height="'+this.options.style.tip.size.height+'" width="'+this.options.style.tip.size.width+'"></canvas>':c.browser.msie&&(a=this.options.style.tip.size.width+","+this.options.style.tip.size.height,l="m"+d[0][0]+","+d[0][1],l+=" l"+d[1][0]+","+d[1][1],l+=" "+d[2][0]+","+d[2][1],a='<v:shape fillcolor="'+e+'" stroked="false" filled="true" path="'+(l+" xe")+'" coordsize="'+a+'" style="width:'+this.options.style.tip.size.width+"px; height:"+this.options.style.tip.size.height+
"px; line-height:0.1px; display:inline-block; behavior:url(#default#VML); vertical-align:"+(/top/.test(b)?"bottom":"top")+'"></v:shape>',a+='<v:image style="behavior:url(#default#VML);"></v:image>',this.elements.contentWrapper.css("position","relative")),this.elements.tip=this.elements.tooltip.find("."+this.options.style.classes.tip).eq(0),this.elements.tip.html(a),c("<canvas>").get(0).getContext&&w.call(this,this.elements.tip.find("canvas:first"),d,e),/top/.test(b)&&(c.browser.msie&&6===parseInt(c.browser.version.charAt(0)))&&
this.elements.tip.css({marginTop:-4}),q.call(this,b))}function w(b,c,d){b=b.get(0).getContext("2d");b.fillStyle=d;b.beginPath();b.moveTo(c[0][0],c[0][1]);b.lineTo(c[1][0],c[1][1]);b.lineTo(c[2][0],c[2][1]);b.fill()}function q(b){var e;!1!==this.options.style.tip.corner&&this.elements.tip&&(b||(b=this.elements.tip.attr("rel")),e=positionAdjust=c.browser.msie?1:0,this.elements.tip.css(b.match(/left|right|top|bottom/)[0],0),/top|bottom/.test(b)?(c.browser.msie&&(positionAdjust=6===parseInt(c.browser.version.charAt(0))?
/top/.test(b)?-3:1:/top/.test(b)?1:2),/Middle/.test(b)?this.elements.tip.css({left:"50%",marginLeft:-(this.options.style.tip.size.width/2)}):/Left/.test(b)?this.elements.tip.css({left:this.options.style.border.radius-e}):/Right/.test(b)&&this.elements.tip.css({right:this.options.style.border.radius+e}),/top/.test(b)?this.elements.tip.css({top:-positionAdjust}):this.elements.tip.css({bottom:positionAdjust})):/left|right/.test(b)&&(c.browser.msie&&(positionAdjust=6===parseInt(c.browser.version.charAt(0))?
1:/left/.test(b)?1:2),/Middle/.test(b)?this.elements.tip.css({top:"50%",marginTop:-(this.options.style.tip.size.height/2)}):/Top/.test(b)?this.elements.tip.css({top:this.options.style.border.radius-e}):/Bottom/.test(b)&&this.elements.tip.css({bottom:this.options.style.border.radius+e}),/left/.test(b)?this.elements.tip.css({left:-positionAdjust}):this.elements.tip.css({right:positionAdjust})),b="padding-"+b.match(/left|right|top|bottom/)[0],e=this.options.style.tip.size[/left|right/.test(b)?"width":
"height"],this.elements.tooltip.css("padding",0),this.elements.tooltip.css(b,e),c.browser.msie&&6==parseInt(c.browser.version.charAt(0))&&(b=parseInt(this.elements.tip.css("margin-top"))||0,b+=parseInt(this.elements.content.css("margin-top"))||0,this.elements.tip.css({marginTop:b})))}function D(b,e,d){var a,l,n,p,f,j,h,m;if("center"==d.corner)return e.position;m=c.extend({},b);j=f=!1;a=m.left<c.fn.qtip.cache.screen.scroll.left;l=m.left+d.dimensions.width+2>=c.fn.qtip.cache.screen.width+c.fn.qtip.cache.screen.scroll.left;
n=m.top<c.fn.qtip.cache.screen.scroll.top;p=m.top+d.dimensions.height+2>=c.fn.qtip.cache.screen.height+c.fn.qtip.cache.screen.scroll.top;h=a&&(/right/i.test(d.corner)||!l);a=l&&(/left/i.test(d.corner)||!a);n=n&&!/top/i.test(d.corner);p=p&&!/bottom/i.test(d.corner);h?(m.left="mouse"!==this.options.position.target?e.position.left+e.dimensions.width:this.cache.mouse.x,f="Left"):a&&(m.left="mouse"!==this.options.position.target?e.position.left-d.dimensions.width:this.cache.mouse.x-d.dimensions.width,
f="Right");n?(m.top="mouse"!==this.options.position.target?e.position.top+e.dimensions.height:this.cache.mouse.y,j="top"):p&&(m.top="mouse"!==this.options.position.target?e.position.top-d.dimensions.height:this.cache.mouse.y-d.dimensions.height,j="bottom");0>m.left&&(m.left=b.left,f=!1);0>m.top&&(m.top=b.top,j=!1);!1!==this.options.style.tip.corner&&(m.corner=new String(d.corner),m.corner.match(/^(right|left)/)?!1!==f&&(m.corner=m.corner.replace(/(left|right)/,f.toLowerCase())):(!1!==f&&(m.corner=
m.corner.replace(/Left|Right|Middle/,f)),!1!==j&&(m.corner=m.corner.replace(/top|bottom/,j))),m.corner!==this.elements.tip.attr("rel")&&A.call(this,m.corner));return m}function s(b,e){var d,a;d=c.extend(!0,{},b);for(a in d)!0===e&&/(tip|classes)/i.test(a)?delete d[a]:!e&&/(width|border|tip|title|classes|user)/i.test(a)&&delete d[a];return d}function B(b){"object"!==typeof b.tip&&(b.tip={corner:b.tip});"object"!==typeof b.tip.size&&(b.tip.size={width:b.tip.size,height:b.tip.size});"object"!==typeof b.border&&
(b.border={width:b.border});"object"!==typeof b.width&&(b.width={value:b.width});"string"==typeof b.width.max&&(b.width.max=parseInt(b.width.max.replace(/([0-9]+)/i,"$1")));"string"==typeof b.width.min&&(b.width.min=parseInt(b.width.min.replace(/([0-9]+)/i,"$1")));"number"==typeof b.tip.size.x&&(b.tip.size.width=b.tip.size.x,delete b.tip.size.x);"number"==typeof b.tip.size.y&&(b.tip.size.height=b.tip.size.y,delete b.tip.size.y);return b}function u(){var b,e;e=[!0,{}];for(b=0;b<arguments.length;b++)e.push(arguments[b]);
for(b=[c.extend.apply(c,e)];"string"==typeof b[0].name;)b.unshift(B(c.fn.qtip.styles[b[0].name]));b.unshift(!0,{classes:{tooltip:"qtip-"+(arguments[0].name||"defaults")}},c.fn.qtip.styles.defaults);b=c.extend.apply(c,b);e=c.browser.msie?1:0;b.tip.size.width+=e;b.tip.size.height+=e;0<b.tip.size.width%2&&(b.tip.size.width+=1);0<b.tip.size.height%2&&(b.tip.size.height+=1);!0===b.tip.corner&&(b.tip.corner="center"===this.options.position.corner.tooltip?!1:this.options.position.corner.tooltip);return b}
function v(b,c,d){c={bottomRight:[[0,0],[c,d],[c,0]],bottomLeft:[[0,0],[c,0],[0,d]],topRight:[[0,d],[c,0],[c,d]],topLeft:[[0,0],[0,d],[c,d]],topMiddle:[[0,d],[c/2,0],[c,d]],bottomMiddle:[[0,0],[c,0],[c/2,d]],rightMiddle:[[0,0],[c,d/2],[0,d]],leftMiddle:[[c,0],[c,d],[0,d/2]]};c.leftTop=c.bottomRight;c.rightTop=c.bottomLeft;c.leftBottom=c.topRight;c.rightBottom=c.topLeft;return c[b]}function x(b){var e;c("<canvas>").get(0).getContext?e={topLeft:[b,b],topRight:[0,b],bottomLeft:[b,0],bottomRight:[0,0]}:
c.browser.msie&&(e={topLeft:[-90,90,0],topRight:[-90,90,-b],bottomLeft:[90,270,0],bottomRight:[90,270,-b]});return e}function E(){var c;c=this.getDimensions();this.elements.bgiframe=this.elements.wrapper.prepend('<iframe class="qtip-bgiframe" frameborder="0" tabindex="-1" src="javascript:false" style="display:block; position:absolute; z-index:-1; filter:alpha(opacity=\'0\'); border: 1px solid red; height:'+c.height+"px; width:"+c.width+'px" />').children(".qtip-bgiframe:first")}c.fn.qtip=function(b,
e){var d,a,l,n,p,f,j,h;if("string"==typeof b){c.isPlainObject(c(this).data("qtip"))&&c.fn.qtip.log.error.call(self,1,c.fn.qtip.constants.NO_TOOLTIP_PRESENT,!1);if("api"==b)return c(this).data("qtip").interfaces[c(this).data("qtip").current];if("interfaces"==b)return c(this).data("qtip").interfaces}else{b||(b={});if("object"!==typeof b.content||b.content.jquery&&0<b.content.length)b.content={text:b.content};"object"!==typeof b.content.title&&(b.content.title={text:b.content.title});"object"!==typeof b.position&&
(b.position={corner:b.position});"object"!==typeof b.position.corner&&(b.position.corner={target:b.position.corner,tooltip:b.position.corner});"object"!==typeof b.show&&(b.show={when:b.show});"object"!==typeof b.show.when&&(b.show.when={event:b.show.when});"object"!==typeof b.show.effect&&(b.show.effect={type:b.show.effect});"object"!==typeof b.hide&&(b.hide={when:b.hide});"object"!==typeof b.hide.when&&(b.hide.when={event:b.hide.when});"object"!==typeof b.hide.effect&&(b.hide.effect={type:b.hide.effect});
"object"!==typeof b.style&&(b.style={name:b.style});b.style=B(b.style);n=c.extend(!0,{},c.fn.qtip.defaults,b);n.style=u.call({options:n},n.style);n.user=c.extend(!0,{},b)}return c(this).each(function(){if("string"==typeof b){if(f=b.toLowerCase(),l=c(this).qtip("interfaces"),"object"==typeof l)if(!0===e&&"destroy"==f)for(;0<l.length;)l[l.length-1].destroy();else{!0!==e&&(l=[c(this).qtip("api")]);for(d=0;d<l.length;d++)"destroy"==f?l[d].destroy():!0===l[d].status.rendered&&("show"==f?l[d].show():"hide"==
f?l[d].hide():"focus"==f?l[d].focus():"disable"==f?l[d].disable(!0):"enable"==f&&l[d].disable(!1))}}else{j=c.extend(!0,{},n);j.hide.effect.length=n.hide.effect.length;j.show.effect.length=n.show.effect.length;!1===j.position.container&&(j.position.container=c(document.body));!1===j.position.target&&(j.position.target=c(this));!1===j.show.when.target&&(j.show.when.target=c(this));!1===j.hide.when.target&&(j.hide.when.target=c(this));a=c.fn.qtip.interfaces.length;for(d=0;d<a;d++)"object"===typeof c(this).data("qtip")&&
c(this).data("qtip");p=new C(c(this),j,a);c.fn.qtip.interfaces[a]=p;c.isPlainObject(c(this).data("qtip"))?("undefined"===typeof c(this).attr("qtip")&&(c(this).data("qtip").current=c(this).data("qtip").interfaces.length),c(this).data("qtip").interfaces.push(p)):c(this).data("qtip",{current:0,interfaces:[p]});!1===j.content.prerender&&!1!==j.show.when.event&&!0!==j.show.ready?j.show.when.target.bind(j.show.when.event+".qtip-"+a+"-create",{qtip:a},function(a){h=c.fn.qtip.interfaces[a.data.qtip];h.options.show.when.target.unbind(h.options.show.when.event+
".qtip-"+a.data.qtip+"-create");h.cache.mouse={x:a.pageX,y:a.pageY};z.call(h);h.options.show.when.target.trigger(h.options.show.when.event)}):(p.cache.mouse={x:j.show.when.target.offset().left,y:j.show.when.target.offset().top},z.call(p))}})};c(document).ready(function(){c.fn.qtip.cache={screen:{scroll:{left:c(window).scrollLeft(),top:c(window).scrollTop()},width:c(window).width(),height:c(window).height()}};var b;c(window).bind("resize scroll",function(e){clearTimeout(b);b=setTimeout(function(){"scroll"===
e.type?c.fn.qtip.cache.screen.scroll={left:c(window).scrollLeft(),top:c(window).scrollTop()}:(c.fn.qtip.cache.screen.width=c(window).width(),c.fn.qtip.cache.screen.height=c(window).height());for(i=0;i<c.fn.qtip.interfaces.length;i++){var b=c.fn.qtip.interfaces[i];!0===b.status.rendered&&(b.options.position.adjust.scroll&&"scroll"===e.type||b.options.position.adjust.resize&&"resize"===e.type)&&b.updatePosition(e,!0)}},100)});c(document).bind("touchstart.qtip",function(b){0===c(b.target).parents("div.qtip").length&&
c(".qtip[unfocus]").each(function(){var d=c(this).qtip("api");c(this).is(":visible")&&(!d.status.disabled&&1<c(b.target).add(d.elements.target).length)&&d.hide(b)})});c(document).bind("mousedown.qtip",function(b){0===c(b.target).parents("div.qtip").length&&c(".qtip[unfocus]").each(function(){var d=c(this).qtip("api");c(this).is(":visible")&&(!d.status.disabled&&1<c(b.target).add(d.elements.target).length)&&d.hide(b)})})});c.fn.qtip.interfaces=[];c.fn.qtip.log={error:function(){return this}};c.fn.qtip.constants=
{};c.fn.qtip.defaults={content:{prerender:!1,text:!1,url:!1,data:null,title:{text:!1,button:!1}},position:{target:!1,corner:{target:"bottomRight",tooltip:"topLeft"},adjust:{x:0,y:0,mouse:!0,screen:!1,scroll:!0,resize:!0},type:"absolute",container:!1},show:{when:{target:!1,event:"mouseover"},effect:{type:"fade",length:100},delay:140,solo:!1,ready:!1},hide:{when:{target:!1,event:"mouseout"},effect:{type:"fade",length:100},delay:0,fixed:!1},api:{beforeRender:function(){},onRender:function(){},beforePositionUpdate:function(){},
onPositionUpdate:function(){},beforeShow:function(){},onShow:function(){},beforeHide:function(){},onHide:function(){},beforeContentUpdate:function(){},onContentUpdate:function(){},beforeContentLoad:function(){},onContentLoad:function(){},beforeTitleUpdate:function(){},onTitleUpdate:function(){},beforeDestroy:function(){},onDestroy:function(){},beforeFocus:function(){},onFocus:function(){}}};c.fn.qtip.styles={defaults:{background:"white",color:"#111",overflow:"hidden",textAlign:"left",width:{min:0,
max:250},padding:"5px 9px",border:{width:1,radius:0,color:"#d3d3d3"},tip:{corner:!1,color:!1,size:{width:13,height:13},opacity:1},title:{background:"#e1e1e1",fontWeight:"bold",padding:"7px 12px"},button:{cursor:"pointer"},classes:{target:"",tip:"qtip-tip",title:"qtip-title",button:"qtip-button",content:"qtip-content",active:"qtip-active"}},cream:{border:{width:3,radius:0,color:"#F9E98E"},title:{background:"#F0DE7D",color:"#A27D35"},background:"#FBF7AA",color:"#A27D35",classes:{tooltip:"qtip-cream"}},
light:{border:{width:3,radius:0,color:"#E2E2E2"},title:{background:"#f1f1f1",color:"#454545"},background:"white",color:"#454545",classes:{tooltip:"qtip-light"}},dark:{border:{width:3,radius:0,color:"#303030"},title:{background:"#404040",color:"#f3f3f3"},background:"#505050",color:"#f3f3f3",classes:{tooltip:"qtip-dark"}},red:{border:{width:3,radius:0,color:"#CE6F6F"},title:{background:"#f28279",color:"#9C2F2F"},background:"#F79992",color:"#9C2F2F",classes:{tooltip:"qtip-red"}},green:{border:{width:3,
radius:0,color:"#A9DB66"},title:{background:"#b9db8c",color:"#58792E"},background:"#CDE6AC",color:"#58792E",classes:{tooltip:"qtip-green"}},blue:{border:{width:3,radius:0,color:"#ADD9ED"},title:{background:"#D0E9F5",color:"#5E99BD"},background:"#E5F6FE",color:"#4D9FBF",classes:{tooltip:"qtip-blue"}}}})(jQuery);