/*	
 *	jQuery carouFredSel 2.2.2
 *	Demo's and documentation:
 *	caroufredsel.frebsite.nl
 *	
 *	Copyright (c) 2010 Fred Heusschen
 *	www.frebsite.nl
 *
 *	Licensed under the MIT license.
 *	http://www.opensource.org/licenses/mit-license.php
 */
(function(f){function v(b){return"right"==b?39:"left"==b?37:"up"==b?38:"down"==b?40:-1}function r(b,c,h){"boolean"!=typeof c&&(c=!1);"boolean"!=typeof h&&(h=!1);"undefined"==typeof b&&(b={});if("string"==typeof b)var a=v(b),b=-1==a?f(b):a;c?("undefined"!=typeof b.jquery&&(b={container:b}),"boolean"==typeof b&&(b={keys:b}),"string"==typeof b.container&&(b.container=f(b.container))):h?("boolean"==typeof b&&(b={play:b}),"number"==typeof b&&(b={pauseDuration:b})):("undefined"!=typeof b.jquery&&(b={button:b}),
"number"==typeof b&&(b={key:b}),"string"==typeof b.button&&(b.button=f(b.button)),"string"==typeof b.key&&(b.key=v(b.key)));return b}function n(b){return f("> *",b)}function w(b,c,h){var a=n(b).filter(":lt("+c.items.visible+")"),b=n(b).filter(":lt("+(c.items.visible+h)+"):gt("+(h-1)+")");return[a,b]}function q(b,c,h){"boolean"!=typeof h&&(h=!1);var a="right"==b.direction||"left"==b.direction?["width","outerWidth","height","outerHeight","left"]:["height","outerHeight","width","outerWidth","top"],i=
0,g=0;h&&"number"==typeof b[a[0]]?i=b[a[0]]:"number"==typeof b.items[a[0]]?i=b.items[a[0]]*c.length:c.each(function(){i+=f(this)[a[1]](!0)});h&&"number"==typeof b[a[2]]?g=b[a[2]]:"number"==typeof b.items[a[2]]?g=b.items[a[2]]:c.each(function(){var c=f(this)[a[3]](!0);g<c&&(g=c)});return[a[0],i,a[2],g,a[4]]}function s(b,c,h,a){var f=q(a,h.filter(":lt("+a.items.visible+")"),!0),h=q(a,h);b.css(f[0],f[1]).css(f[2],f[3]);c.css(h[0],2*h[1]).css(h[2],h[3])}function m(b){b="carouFredSel: "+b;if(window.console&&
window.console.log)window.console.log(b);else try{console.log(b)}catch(c){}}f.fn.carouFredSel=function(b){if(1<this.length)return this.each(function(){f(this).carouFredSel(b)});this.init=function(){t="up"==a.direction||"left"==a.direction?"next":"prev";"object"!=typeof a.items&&(a.items={visible:a.items});a.items.width||(a.items.width=i.outerWidth(!0));a.items.height||(a.items.height=i.outerHeight(!0));"number"!=typeof a.scroll.duration&&(a.scroll.duration=500);"number"!=typeof a.scroll.items&&(a.scroll.items=
a.items.visible);a.auto=r(a.auto,!1,!0);a.prev=r(a.prev);a.next=r(a.next);a.pagination=r(a.pagination,!0);a.auto=f.extend({},a.scroll,a.auto);a.prev=f.extend({},a.scroll,a.prev);a.next=f.extend({},a.scroll,a.next);a.pagination=f.extend({},a.scroll,a.pagination);"function"!=typeof a.pagination.anchorBuilder&&(a.pagination.anchorBuilder=f.fn.carouFredSel.pageAnchorBuilder);"boolean"!=typeof a.pagination.keys&&(a.pagination.keys=!1);"boolean"!=typeof a.auto.play&&(a.auto.play=!0);"boolean"!=typeof a.auto.nap&&
(a.auto.nap=!0);"number"!=typeof a.auto.delay&&(a.auto.delay=0);"number"!=typeof a.auto.pauseDuration&&(a.auto.pauseDuration=10>a.auto.duration?2500:5*a.auto.duration);return this};this.build=function(){h.css({position:"relative",overflow:"hidden"});c.css({position:"absolute"});s(h,c,i,a);return this};this.bind_events=function(){c.bind("pause",function(){null!=u&&clearTimeout(u)}).bind("play",function(b,d,e){a.auto.play&&("prev"!=d&&"next"!=d&&(d=t),"number"!=typeof e&&(e=0),u=setTimeout(function(){c.is(":animated")?
c.trigger("pause").trigger("play",d):c.trigger(d,a.auto)},a.auto.pauseDuration+e))}).bind("prev",function(b,d,e){if(!c.is(":animated"))if(a.items.visible>=g)m("Not enough items: not scrolling");else if("number"==typeof d&&(e=d),"object"!=typeof d&&(d=a.prev),"number"!=typeof e&&(e=d.items),"number"!=typeof e)m("Not a valid number: not scrolling");else{c.find("> *:gt("+(g-e-1)+")").prependTo(c);g<a.items.visible+e&&c.find("> *:lt("+(a.items.visible+e-g)+")").clone(!0).appendTo(c);j-=e;0>j&&(j+=g);
var b=w(c,a,e),l=q(a,n(c).filter(":lt("+e+")")),f=q(a,b[0],!0),i={},p={},k=d.duration;"auto"==k?k=a.scroll.duration/a.scroll.items*e:10>k&&(k=l[1]/k);i[l[4]]=0;p[l[0]]=f[1];p[l[2]]=f[3];if(d.onBefore)d.onBefore(b[1],b[0],f[1],f[3],k);h.animate(p,{duration:k,easing:d.easing});c.data("cfs_numItems",e).data("cfs_slideObj",d).data("cfs_oldItems",b[1]).data("cfs_newItems",b[0]).data("cfs_w_siz1",f[1]).data("cfs_w_siz2",f[3]).css(l[4],-l[1]).animate(i,{duration:k,easing:d.easing,complete:function(){g<a.items.visible+
c.data("cfs_numItems")&&c.find("> *:gt("+(g-1)+")").remove();if(c.data("cfs_slideObj").onAfter)c.data("cfs_slideObj").onAfter(c.data("cfs_oldItems"),c.data("cfs_newItems"),c.data("cfs_w_siz1"),c.data("cfs_w_siz2"))}});c.trigger("updatePageStatus").trigger("pause").trigger("play",["",k])}}).bind("next",function(b,d,e){if(!c.is(":animated"))if(a.items.visible>=g)m("Not enough items: not scrolling");else if("number"==typeof d&&(e=d),"object"!=typeof d&&(d=a.next),"number"!=typeof e&&(e=d.items),"number"!=
typeof e)m("Not a valid number: not scrolling");else{g<a.items.visible+e&&c.find("> *:lt("+(a.items.visible+e-g)+")").clone(!0).appendTo(c);j+=e;j>=g&&(j-=g);var b=w(c,a,e),f=q(a,n(c).filter(":lt("+e+")")),i=q(a,b[1],!0),x={},p={},k=d.duration;"auto"==k?k=a.scroll.duration/a.scroll.items*e:10>k&&(k=f[1]/k);x[f[4]]=-f[1];p[f[0]]=i[1];p[f[2]]=i[3];if(d.onBefore)d.onBefore(b[0],b[1],i[1],i[3],k);h.animate(p,{duration:k,easing:d.easing});c.data("cfs_numItems",e).data("cfs_slideObj",d).data("cfs_oldItems",
b[0]).data("cfs_newItems",b[1]).data("cfs_w_siz1",i[1]).data("cfs_w_siz2",i[3]).animate(x,{duration:k,easing:d.easing,complete:function(){if(c.data("cfs_slideObj").onAfter)c.data("cfs_slideObj").onAfter(c.data("cfs_oldItems"),c.data("cfs_newItems"),c.data("cfs_w_siz1"),c.data("cfs_w_siz2"));g<a.items.visible+c.data("cfs_numItems")&&c.find("> *:gt("+(g-1)+")").remove();c.css(f[4],0).find("> *:lt("+c.data("cfs_numItems")+")").appendTo(c)}});c.trigger("updatePageStatus").trigger("pause").trigger("play",
["",k])}}).bind("scrollTo",function(a,d,b,f){c.is(":animated")||("string"==typeof d&&(d=parseInt(d)),"object"==typeof d?d=c.find("> *").index(d):"number"==typeof d&&(d+=-j+g,d>=g&&(d-=g)),"number"!=typeof d||-1==d?m("Not a valid number."):("string"==typeof b&&(b=parseInt(b)),"number"!=typeof b&&(b=0),"object"!=typeof f&&(f=!1),d+=b,0>d&&(d+=g),d>=g&&(d-=g),0!=d&&(d<g/2?c.trigger("next",[f,d]):c.trigger("prev",[f,g-d]))))}).bind("slideTo",function(a,d,b,f){c.trigger("scrollTo",[d,b,f])}).bind("insertItem",
function(b,d,e){"string"==typeof d&&(d=f(d));"object"!=typeof d||"undefined"==typeof d.jquery||0==d.length?m("Not a valid object."):("undefined"==typeof e&&(e="after"),"number"==typeof e&&(e-=1),"string"==typeof e&&(e="before"==e?g-1:"after"==e?a.items.visible-1:"end"==e?g-j-1:f(e)),"object"==typeof e&&(e=c.find("> *").index(e)-1),"number"!=typeof e?m("Not a valid number."):(b=g-j,b>=g&&(b-=g),e>=b&&0<b&&(j+=d.length),b=c.find("> *"),2>b.length?-1==e?c.prepend(d):c.append(d):-1==e?b.filter(":nth(0)").before(d):
b.filter(":nth("+e+")").after(d),i=n(c),g=i.length,s(h,c,i,a),c.trigger("updatePageStatus",!0)))}).bind("removeItem",function(b,d){"object"==typeof d&&"undefined"==typeof d.jquery&&(d=f(d));"string"==typeof d&&(d=f(d));"number"==typeof d&&(d=c.find("> *:nth("+d+")"));if("object"!=typeof d||"undefined"==typeof d.jquery||0==d.length)m("Not a valid object.");else{var e=c.find("> *").index(d),l=g-j;l>=g&&(l-=g);e>=l&&0<l?j-=d.length:0==l-d.length&&(j=0);d.remove();i=n(c);g=i.length;s(h,c,i,a);c.trigger("updatePageStatus",
!0)}}).bind("updatePageStatus",function(b,d){if(!a.pagination.container)return!1;if("boolean"==typeof d&&d){a.pagination.container.find("> *").remove();for(var e=0;e<Math.ceil(g/a.items.visible);e++)a.pagination.container.append(a.pagination.anchorBuilder(e+1));a.pagination.container.find("> *").each(function(b){f(this).unbind("click").click(function(){c.trigger("scrollTo",[b*a.items.visible,0,a.pagination]);return!1})})}e=Math.round(j/a.items.visible);a.pagination.container.find("> *").removeClass("selected").filter(":nth("+
e+")").addClass("selected")});a.auto.pauseOnHover&&a.auto.play&&c.hover(function(){c.trigger("pause")},function(){c.trigger("play")});a.prev.button&&(a.prev.button.click(function(){c.trigger("prev");return!1}),a.prev.pauseOnHover&&a.auto.play&&a.prev.button.hover(function(){c.trigger("pause")},function(){c.trigger("play")}));a.next.button&&(a.next.button.click(function(){c.trigger("next");return!1}),a.next.pauseOnHover&&a.auto.play&&a.next.button.hover(function(){c.trigger("pause")},function(){c.trigger("play")}));
a.pagination.container&&(c.trigger("updatePageStatus",!0),a.pagination.pauseOnHover&&a.auto.play&&a.pagination.container.hover(function(){c.trigger("pause")},function(){c.trigger("play")}));(a.next.key||a.prev.key)&&f(document).keyup(function(b){b=b.keyCode;b==a.next.key&&c.trigger("next");b==a.prev.key&&c.trigger("prev")});a.pagination.keys&&f(document).keyup(function(b){b=b.keyCode;49<=b&&58>b&&(b=(b-49)*a.items.visible,b<=g&&c.trigger("scrollTo",[b,0,a.pagination]))});a.auto.play&&(c.trigger("play",
[t,a.auto.delay]),f.fn.nap&&a.auto.nap&&c.nap("pause","play"));return this};this.destroy=function(){c.css({width:"auto",height:"auto",position:"static"});c.unbind("pause").unbind("play").unbind("prev").unbind("next").unbind("scrollTo").unbind("slideTo").unbind("insertItem").unbind("removeItem").unbind("updatePageStatus");h.replaceWith(c);return this};this.configuration=function(b,c){if("undefined"==typeof b)return a;for(var e=b.split("."),f=a,g="",h=0;h<e.length;h++)g=e[h],h<e.length-1&&(f=f[g]);
if("undefined"==typeof c)return f[g];f[g]=c;this.init();this.build();return this};var c=f(this),h=c.wrap('<div class="caroufredsel_wrapper" />').parent(),a=f.extend(!0,{},f.fn.carouFredSel.defaults,b),i=n(c),g=i.length,j=0,u=null,t="next";this.init();this.build();this.bind_events();return this};f.fn.carouFredSel.defaults={direction:"left",items:{visible:5},scroll:{easing:"swing",pauseOnHover:!1}};f.fn.carouFredSel.pageAnchorBuilder=function(b){return'<a href="#"><span>'+b+"</span></a>"}})(jQuery);