//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.237.
// 
#pragma warning disable 1591

namespace DotNetNuke.Modules.Socios_MediaSearch.SociosTranslationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TranslateServicePortBinding", Namespace="http://socios/")]
    public partial class TranslateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback translateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLanguagesForTranslateOperationCompleted;
        
        private System.Threading.SendOrPostCallback detectOperationCompleted;
        
        private System.Threading.SendOrPostCallback translateMediaItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TranslateService() {
            this.Url = global::DotNetNuke.Modules.Socios_MediaSearch.Properties.Settings.Default.Socios_MediaSearch_SociosTranslationService_TranslateService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event translateCompletedEventHandler translateCompleted;
        
        /// <remarks/>
        public event getLanguagesForTranslateCompletedEventHandler getLanguagesForTranslateCompleted;
        
        /// <remarks/>
        public event detectCompletedEventHandler detectCompleted;
        
        /// <remarks/>
        public event translateMediaItemCompletedEventHandler translateMediaItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://socios/", ResponseNamespace="http://socios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string translate([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string bingAppId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string text, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string target) {
            object[] results = this.Invoke("translate", new object[] {
                        bingAppId,
                        text,
                        source,
                        target});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void translateAsync(string bingAppId, string text, string source, string target) {
            this.translateAsync(bingAppId, text, source, target, null);
        }
        
        /// <remarks/>
        public void translateAsync(string bingAppId, string text, string source, string target, object userState) {
            if ((this.translateOperationCompleted == null)) {
                this.translateOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateOperationCompleted);
            }
            this.InvokeAsync("translate", new object[] {
                        bingAppId,
                        text,
                        source,
                        target}, this.translateOperationCompleted, userState);
        }
        
        private void OntranslateOperationCompleted(object arg) {
            if ((this.translateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateCompleted(this, new translateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://socios/", ResponseNamespace="http://socios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getLanguagesForTranslate([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string bingAppId) {
            object[] results = this.Invoke("getLanguagesForTranslate", new object[] {
                        bingAppId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLanguagesForTranslateAsync(string bingAppId) {
            this.getLanguagesForTranslateAsync(bingAppId, null);
        }
        
        /// <remarks/>
        public void getLanguagesForTranslateAsync(string bingAppId, object userState) {
            if ((this.getLanguagesForTranslateOperationCompleted == null)) {
                this.getLanguagesForTranslateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLanguagesForTranslateOperationCompleted);
            }
            this.InvokeAsync("getLanguagesForTranslate", new object[] {
                        bingAppId}, this.getLanguagesForTranslateOperationCompleted, userState);
        }
        
        private void OngetLanguagesForTranslateOperationCompleted(object arg) {
            if ((this.getLanguagesForTranslateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLanguagesForTranslateCompleted(this, new getLanguagesForTranslateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://socios/", ResponseNamespace="http://socios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detect([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string bingAppId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string text) {
            object[] results = this.Invoke("detect", new object[] {
                        bingAppId,
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void detectAsync(string bingAppId, string text) {
            this.detectAsync(bingAppId, text, null);
        }
        
        /// <remarks/>
        public void detectAsync(string bingAppId, string text, object userState) {
            if ((this.detectOperationCompleted == null)) {
                this.detectOperationCompleted = new System.Threading.SendOrPostCallback(this.OndetectOperationCompleted);
            }
            this.InvokeAsync("detect", new object[] {
                        bingAppId,
                        text}, this.detectOperationCompleted, userState);
        }
        
        private void OndetectOperationCompleted(object arg) {
            if ((this.detectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.detectCompleted(this, new detectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://socios/", ResponseNamespace="http://socios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MediaItem translateMediaItem([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string bingAppId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] MediaItem arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string target) {
            object[] results = this.Invoke("translateMediaItem", new object[] {
                        bingAppId,
                        arg1,
                        source,
                        target});
            return ((MediaItem)(results[0]));
        }
        
        /// <remarks/>
        public void translateMediaItemAsync(string bingAppId, MediaItem arg1, string source, string target) {
            this.translateMediaItemAsync(bingAppId, arg1, source, target, null);
        }
        
        /// <remarks/>
        public void translateMediaItemAsync(string bingAppId, MediaItem arg1, string source, string target, object userState) {
            if ((this.translateMediaItemOperationCompleted == null)) {
                this.translateMediaItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateMediaItemOperationCompleted);
            }
            this.InvokeAsync("translateMediaItem", new object[] {
                        bingAppId,
                        arg1,
                        source,
                        target}, this.translateMediaItemOperationCompleted, userState);
        }
        
        private void OntranslateMediaItemOperationCompleted(object arg) {
            if ((this.translateMediaItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateMediaItemCompleted(this, new translateMediaItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sociosproject.eu/sociosVoc/")]
    public partial class MediaItem {
        
        private ObjectId idField;
        
        private string titleField;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private string thumbnailUrlField;
        
        private string descriptionField;
        
        private string durationField;
        
        private Address locationField;
        
        private string languageField;
        
        private ObjectId albumIdField;
        
        private long fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        private System.DateTime startTimeField;
        
        private bool startTimeFieldSpecified;
        
        private string ratingField;
        
        private string numVotesField;
        
        private string numCommentsField;
        
        private string numViewsField;
        
        private string tagsField;
        
        private string taggedPeopleField;
        
        private string mimeTypeField;
        
        private MediaItemType typeField;
        
        private bool typeFieldSpecified;
        
        private string urlField;
        
        /// <remarks/>
        public ObjectId id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string thumbnailUrl {
            get {
                return this.thumbnailUrlField;
            }
            set {
                this.thumbnailUrlField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public Address location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public ObjectId albumId {
            get {
                return this.albumIdField;
            }
            set {
                this.albumIdField = value;
            }
        }
        
        /// <remarks/>
        public long fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileSizeSpecified {
            get {
                return this.fileSizeFieldSpecified;
            }
            set {
                this.fileSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string numVotes {
            get {
                return this.numVotesField;
            }
            set {
                this.numVotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string numComments {
            get {
                return this.numCommentsField;
            }
            set {
                this.numCommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string numViews {
            get {
                return this.numViewsField;
            }
            set {
                this.numViewsField = value;
            }
        }
        
        /// <remarks/>
        public string tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public string taggedPeople {
            get {
                return this.taggedPeopleField;
            }
            set {
                this.taggedPeopleField = value;
            }
        }
        
        /// <remarks/>
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        public MediaItemType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sociosproject.eu/sociosVoc/")]
    public partial class ObjectId {
        
        private string idField;
        
        private Source sourceField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Source source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sociosproject.eu/sociosVoc/")]
    public partial class Source {
        
        private KnownSns knownSnsField;
        
        private bool knownSnsFieldSpecified;
        
        private OpenSocialSns openSocialSnsIdField;
        
        private string otherIdField;
        
        /// <remarks/>
        public KnownSns knownSns {
            get {
                return this.knownSnsField;
            }
            set {
                this.knownSnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool knownSnsSpecified {
            get {
                return this.knownSnsFieldSpecified;
            }
            set {
                this.knownSnsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public OpenSocialSns openSocialSnsId {
            get {
                return this.openSocialSnsIdField;
            }
            set {
                this.openSocialSnsIdField = value;
            }
        }
        
        /// <remarks/>
        public string otherId {
            get {
                return this.otherIdField;
            }
            set {
                this.otherIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sociosproject.eu/sociosVoc/")]
    public enum KnownSns {
        
        /// <remarks/>
        FACEBOOK,
        
        /// <remarks/>
        YOUTUBE,
        
        /// <remarks/>
        TWITTER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sociosproject.eu/sociosVoc/")]
    public partial class OpenSocialSns {
        
        private string baseUriField;
        
        /// <remarks/>
        public string baseUri {
            get {
                return this.baseUriField;
            }
            set {
                this.baseUriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sociosproject.eu/sociosVoc/")]
    public partial class Address {
        
        private string countryField;
        
        private string extendedAddressField;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private string localityField;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private string poBoxField;
        
        private string postalCodeField;
        
        private bool primaryField;
        
        private bool primaryFieldSpecified;
        
        private string regionField;
        
        private string streetAddressField;
        
        private string typeField;
        
        private string formattedField;
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string extendedAddress {
            get {
                return this.extendedAddressField;
            }
            set {
                this.extendedAddressField = value;
            }
        }
        
        /// <remarks/>
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string poBox {
            get {
                return this.poBoxField;
            }
            set {
                this.poBoxField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool primarySpecified {
            get {
                return this.primaryFieldSpecified;
            }
            set {
                this.primaryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string streetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string formatted {
            get {
                return this.formattedField;
            }
            set {
                this.formattedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sociosproject.eu/sociosVoc/")]
    public enum MediaItemType {
        
        /// <remarks/>
        AUDIO,
        
        /// <remarks/>
        IMAGE,
        
        /// <remarks/>
        VIDEO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void translateCompletedEventHandler(object sender, translateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getLanguagesForTranslateCompletedEventHandler(object sender, getLanguagesForTranslateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLanguagesForTranslateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLanguagesForTranslateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void detectCompletedEventHandler(object sender, detectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal detectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void translateMediaItemCompletedEventHandler(object sender, translateMediaItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateMediaItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateMediaItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MediaItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MediaItem)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591