package eu.sociosproject.sociosapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-03-26T15:30:33.328+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "sociosApi", 
                  wsdlLocation = "./wsdl/socios-core-api.wsdl",
                  targetNamespace = "http://www.sociosproject.eu/sociosApi/") 
public class SociosApi_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sociosproject.eu/sociosApi/", "sociosApi");
    public final static QName SociosApiSOAP = new QName("http://www.sociosproject.eu/sociosApi/", "sociosApiSOAP");
    static {
        URL url = null;
        try {
            url = new URL("./wsdl/socios-core-api.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SociosApi_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "./wsdl/socios-core-api.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SociosApi_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SociosApi_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SociosApi_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SociosApi
     */
    @WebEndpoint(name = "sociosApiSOAP")
    public SociosApi getSociosApiSOAP() {
        return super.getPort(SociosApiSOAP, SociosApi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SociosApi
     */
    @WebEndpoint(name = "sociosApiSOAP")
    public SociosApi getSociosApiSOAP(WebServiceFeature... features) {
        return super.getPort(SociosApiSOAP, SociosApi.class, features);
    }

}
