
package eu.sociosproject.sociosapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-03-26T15:30:32.981+02:00
 * Generated source version: 2.5.0
 */

@WebFault(name = "fault", targetNamespace = "http://www.sociosproject.eu/sociosApi/")
public class SociosException extends Exception {
    
    private eu.sociosproject.sociosvoc.SociosException fault;

    public SociosException() {
        super();
    }
    
    public SociosException(String message) {
        super(message);
    }
    
    public SociosException(String message, Throwable cause) {
        super(message, cause);
    }

    public SociosException(String message, eu.sociosproject.sociosvoc.SociosException fault) {
        super(message);
        this.fault = fault;
    }

    public SociosException(String message, eu.sociosproject.sociosvoc.SociosException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public eu.sociosproject.sociosvoc.SociosException getFaultInfo() {
        return this.fault;
    }
}
