package eu.sociosproject.sociosapi;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-03-26T15:30:33.238+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://www.sociosproject.eu/sociosApi/", name = "sociosApi")
@XmlSeeAlso({eu.sociosproject.sociosvoc.ObjectFactory.class, ObjectFactory.class})
public interface SociosApi {

    @WebResult(name = "person", targetNamespace = "http://www.sociosproject.eu/sociosVoc/")
    @RequestWrapper(localName = "FindPersons", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.FindPersons")
    @WebMethod(operationName = "FindPersons", action = "http://www.sociosproject.eu/sociosApi/FindPersons")
    @ResponseWrapper(localName = "personList", targetNamespace = "http://www.sociosproject.eu/sociosVoc/", className = "eu.sociosproject.sociosvoc.PersonList")
    public java.util.List<eu.sociosproject.sociosvoc.Person> findPersons(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "personFilter", targetNamespace = "")
        eu.sociosproject.sociosvoc.PersonFilter personFilter,
        @WebParam(name = "mediaItemIdList", targetNamespace = "")
        eu.sociosproject.sociosvoc.MediaItemIdList mediaItemIdList
    ) throws SociosException;

    @WebResult(name = "person", targetNamespace = "http://www.sociosproject.eu/sociosVoc/")
    @RequestWrapper(localName = "MyConnectedPersons", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.MyConnectedPersons")
    @WebMethod(operationName = "MyConnectedPersons", action = "http://www.sociosproject.eu/sociosApi/MyConnectedPersons")
    @ResponseWrapper(localName = "personList", targetNamespace = "http://www.sociosproject.eu/sociosVoc/", className = "eu.sociosproject.sociosvoc.PersonList")
    public java.util.List<eu.sociosproject.sociosvoc.Person> myConnectedPersons(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "personId", targetNamespace = "")
        eu.sociosproject.sociosvoc.ObjectId personId
    ) throws SociosException;

    @WebResult(name = "activity", targetNamespace = "http://www.sociosproject.eu/sociosVoc/")
    @RequestWrapper(localName = "GetActivities", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.GetActivities")
    @WebMethod(operationName = "GetActivities", action = "http://www.sociosproject.eu/sociosApi/GetActivities")
    @ResponseWrapper(localName = "activityList", targetNamespace = "http://www.sociosproject.eu/sociosVoc/", className = "eu.sociosproject.sociosvoc.ActivityList")
    public java.util.List<eu.sociosproject.sociosvoc.Activity> getActivities(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "activityIds", targetNamespace = "")
        eu.sociosproject.sociosvoc.ActivityIdList activityIds
    ) throws SociosException;

    @WebResult(name = "person", targetNamespace = "http://www.sociosproject.eu/sociosVoc/")
    @RequestWrapper(localName = "GetPersons", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.GetPersons")
    @WebMethod(operationName = "GetPersons", action = "http://www.sociosproject.eu/sociosApi/GetPersons")
    @ResponseWrapper(localName = "personList", targetNamespace = "http://www.sociosproject.eu/sociosVoc/", className = "eu.sociosproject.sociosvoc.PersonList")
    public java.util.List<eu.sociosproject.sociosvoc.Person> getPersons(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "personIdList", targetNamespace = "")
        eu.sociosproject.sociosvoc.PersonIdList personIdList
    ) throws SociosException;

    @WebResult(name = "mediaItem", targetNamespace = "http://www.sociosproject.eu/sociosVoc/")
    @RequestWrapper(localName = "FindMediaItems", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.FindMediaItems")
    @WebMethod(operationName = "FindMediaItems", action = "http://www.sociosproject.eu/sociosApi/FindMediaItems")
    @ResponseWrapper(localName = "mediaItemList", targetNamespace = "http://www.sociosproject.eu/sociosVoc/", className = "eu.sociosproject.sociosvoc.MediaItemList")
    public java.util.List<eu.sociosproject.sociosvoc.MediaItem> findMediaItems(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "filterMediaItem", targetNamespace = "")
        eu.sociosproject.sociosvoc.MediaItemFilter filterMediaItem,
        @WebParam(name = "filterPerson", targetNamespace = "")
        eu.sociosproject.sociosvoc.PersonFilter filterPerson,
        @WebParam(name = "personIdList", targetNamespace = "")
        eu.sociosproject.sociosvoc.PersonIdList personIdList
    ) throws SociosException;

    @WebResult(name = "activity", targetNamespace = "http://www.sociosproject.eu/sociosVoc/")
    @RequestWrapper(localName = "FindConnectedActivities", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.FindConnectedActivities")
    @WebMethod(operationName = "FindConnectedActivities", action = "http://www.sociosproject.eu/sociosApi/FindConnectedActivities")
    @ResponseWrapper(localName = "activityList", targetNamespace = "http://www.sociosproject.eu/sociosVoc/", className = "eu.sociosproject.sociosvoc.ActivityList")
    public java.util.List<eu.sociosproject.sociosvoc.Activity> findConnectedActivities(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "activityIds", targetNamespace = "")
        eu.sociosproject.sociosvoc.ActivityIdList activityIds
    ) throws SociosException;

    @WebResult(name = "person", targetNamespace = "http://www.sociosproject.eu/sociosVoc/")
    @RequestWrapper(localName = "ConnectedPersons", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.ConnectedPersons")
    @WebMethod(operationName = "ConnectedPersons", action = "http://www.sociosproject.eu/sociosApi/ConnectedPersons")
    @ResponseWrapper(localName = "personList", targetNamespace = "http://www.sociosproject.eu/sociosVoc/", className = "eu.sociosproject.sociosvoc.PersonList")
    public java.util.List<eu.sociosproject.sociosvoc.Person> connectedPersons(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "personId", targetNamespace = "")
        eu.sociosproject.sociosvoc.ObjectId personId
    ) throws SociosException;

    @WebResult(name = "activity", targetNamespace = "http://www.sociosproject.eu/sociosVoc/")
    @RequestWrapper(localName = "FindActivities", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.FindActivities")
    @WebMethod(operationName = "FindActivities", action = "http://www.sociosproject.eu/sociosApi/FindActivities")
    @ResponseWrapper(localName = "activityList", targetNamespace = "http://www.sociosproject.eu/sociosVoc/", className = "eu.sociosproject.sociosvoc.ActivityList")
    public java.util.List<eu.sociosproject.sociosvoc.Activity> findActivities(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "activityFilter", targetNamespace = "")
        eu.sociosproject.sociosvoc.ActivityFilter activityFilter,
        @WebParam(name = "personFilter", targetNamespace = "")
        eu.sociosproject.sociosvoc.PersonFilter personFilter,
        @WebParam(name = "mediaItemIdList", targetNamespace = "")
        eu.sociosproject.sociosvoc.MediaItemIdList mediaItemIdList,
        @WebParam(name = "personIdList", targetNamespace = "")
        eu.sociosproject.sociosvoc.PersonIdList personIdList
    ) throws SociosException;

    @Oneway
    @RequestWrapper(localName = "InteractWithUser", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.InteractWithUser")
    @WebMethod(operationName = "InteractWithUser", action = "http://www.sociosproject.eu/sociosApi/InteractWithUser")
    public void interactWithUser(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "personId", targetNamespace = "")
        eu.sociosproject.sociosvoc.ObjectId personId,
        @WebParam(name = "mediaItemId", targetNamespace = "")
        eu.sociosproject.sociosvoc.ObjectId mediaItemId,
        @WebParam(name = "messageText", targetNamespace = "")
        java.lang.String messageText
    );

    @WebResult(name = "mediaItem", targetNamespace = "http://www.sociosproject.eu/sociosVoc/")
    @RequestWrapper(localName = "GetMediaItems", targetNamespace = "http://www.sociosproject.eu/sociosApi/", className = "eu.sociosproject.sociosapi.GetMediaItems")
    @WebMethod(operationName = "GetMediaItems", action = "http://www.sociosproject.eu/sociosApi/GetMediaItems")
    @ResponseWrapper(localName = "mediaItemList", targetNamespace = "http://www.sociosproject.eu/sociosVoc/", className = "eu.sociosproject.sociosvoc.MediaItemList")
    public java.util.List<eu.sociosproject.sociosvoc.MediaItem> getMediaItems(
        @WebParam(name = "sociosApiUserKey", targetNamespace = "")
        java.lang.String sociosApiUserKey,
        @WebParam(name = "mediaItemIdList", targetNamespace = "")
        eu.sociosproject.sociosvoc.MediaItemIdList mediaItemIdList
    ) throws SociosException;
}
